/* The following code was generated by JFlex 1.6.1 */

/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").  
 * You may not use this file except in compliance with the License.
 *
 * See LICENSE.txt included in this distribution for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at LICENSE.txt.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

/*
 * Copyright (c) 2015, Oracle and/or its affiliates. All rights reserved.
 */

/*
 * Cross reference an Erlang file
 */

package com.grantingersoll.opengrok.analysis.erlang;
import com.grantingersoll.opengrok.analysis.JFlexXref;
import java.io.IOException;
import java.io.Writer;
import java.io.Reader;
import com.grantingersoll.opengrok.web.Util;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/Users/grantingersoll/projects/OpenGrok/src/org/opensolaris/opengrok/analysis/erlang/ErlangXref.lex</tt>
 */
public class ErlangXref extends JFlexXref {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int COMMENT = 4;
  public static final int QATOM = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\1\63\1\1\1\2\22\0\1\1\1\26\1\53"+
    "\1\25\1\26\1\55\1\57\1\54\1\51\1\52\1\26\1\46\1\26"+
    "\1\27\1\30\1\44\1\23\1\40\1\20\1\22\3\24\3\21\1\64"+
    "\1\26\1\60\1\26\1\61\1\50\1\5\1\33\1\17\1\11\1\14"+
    "\1\15\1\45\1\4\1\32\1\7\1\47\1\4\1\12\1\42\1\10"+
    "\1\47\1\34\1\4\1\31\1\36\1\43\1\13\2\4\1\41\1\37"+
    "\1\4\1\62\1\56\2\62\1\16\1\62\1\33\1\17\1\11\1\14"+
    "\1\15\1\45\1\4\1\32\1\7\1\47\1\4\1\12\1\42\1\10"+
    "\1\47\1\34\1\4\1\31\1\36\1\43\1\13\2\4\1\41\1\37"+
    "\1\4\3\62\1\26\6\0\1\63\252\0\2\6\115\0\1\35\u1ea8\0"+
    "\1\63\1\63\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\2\3\2\4\4\5\2\4\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\5\4\1\14\1\4"+
    "\1\2\2\15\1\16\1\4\1\17\1\5\3\0\2\5"+
    "\12\0\1\20\1\21\1\22\1\5\1\0\3\5\1\0"+
    "\1\23\10\0\1\5\6\0\1\24\3\0\1\25\3\26"+
    "\3\0\1\26\4\0\1\27\31\0\1\30";

  private static int [] zzUnpackAction() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\u0109\0\u013e\0\324"+
    "\0\u0173\0\324\0\u01a8\0\u01dd\0\u0212\0\u0247\0\u027c\0\u02b1"+
    "\0\324\0\324\0\324\0\324\0\324\0\324\0\u02e6\0\u031b"+
    "\0\u0350\0\u0385\0\u03ba\0\324\0\u03ef\0\u0424\0\u0459\0\324"+
    "\0\324\0\u048e\0\u0173\0\u04c3\0\u04f8\0\u052d\0\u0562\0\u0597"+
    "\0\u05cc\0\u0601\0\u0636\0\u02e6\0\u066b\0\u06a0\0\u06d5\0\u031b"+
    "\0\u070a\0\u073f\0\u0774\0\324\0\324\0\324\0\u07a9\0\u07de"+
    "\0\u052d\0\u0813\0\u0848\0\u087d\0\u0636\0\u08b2\0\u08e7\0\u091c"+
    "\0\u0951\0\u0986\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4"+
    "\0\u0af9\0\u0b2e\0\u0b63\0\u0b98\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c"+
    "\0\u0ac4\0\u02e6\0\u0ca1\0\u0cd6\0\u0d0b\0\u0d40\0\u0d75\0\324"+
    "\0\u0daa\0\u0ddf\0\u0e14\0\u0e49\0\u0e14\0\u0e7e\0\u0eb3\0\u0ee8"+
    "\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\u1026\0\u105b\0\u1090"+
    "\0\u10c5\0\u10fa\0\u112f\0\u1164\0\u1199\0\u11ce\0\u1203\0\u1238"+
    "\0\u126d\0\u12a2\0\u12d7\0\u130c\0\u1341\0\u1376\0\324";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\5\11\11"+
    "\1\13\1\14\1\15\1\16\1\14\2\12\1\17\1\12"+
    "\4\11\1\5\2\11\1\13\3\11\1\12\1\11\1\12"+
    "\1\11\1\20\2\12\1\21\1\22\1\23\1\12\1\24"+
    "\1\25\1\26\1\12\1\0\1\12\1\5\1\6\1\7"+
    "\1\10\1\27\1\12\1\5\7\27\1\30\1\27\5\30"+
    "\2\12\2\30\1\27\1\31\2\27\1\5\2\27\1\30"+
    "\3\27\1\32\1\33\1\12\1\27\3\12\1\34\2\12"+
    "\1\35\1\24\1\25\1\26\1\12\1\0\1\12\1\5"+
    "\1\36\1\37\1\40\1\27\1\12\1\5\7\27\1\30"+
    "\1\27\5\30\2\12\2\30\1\27\1\31\2\27\1\5"+
    "\2\27\1\30\3\27\1\32\1\33\1\12\1\27\7\12"+
    "\1\24\1\25\1\26\1\12\1\0\1\12\1\5\1\6"+
    "\1\7\1\10\1\27\1\12\1\5\7\27\1\30\1\27"+
    "\5\30\2\12\2\30\1\27\1\31\2\27\1\5\2\27"+
    "\1\30\3\27\1\32\1\33\1\12\1\27\4\12\1\41"+
    "\1\12\1\42\1\24\1\25\1\26\1\12\1\0\1\12"+
    "\66\0\1\6\1\7\1\10\64\0\1\10\65\0\2\43"+
    "\1\0\16\43\4\0\4\43\1\0\6\43\1\0\1\43"+
    "\1\0\1\43\27\0\1\44\2\0\1\45\1\0\1\44"+
    "\5\14\1\46\2\0\1\47\7\0\1\14\1\44\5\0"+
    "\1\44\27\0\1\44\2\0\1\45\1\0\1\44\5\50"+
    "\1\46\2\0\1\47\7\0\1\50\1\44\5\0\1\44"+
    "\27\0\1\44\2\0\1\45\1\0\1\44\1\14\1\50"+
    "\3\14\1\46\2\0\1\47\7\0\1\14\1\44\5\0"+
    "\1\44\27\0\1\44\2\0\1\45\1\0\1\44\5\50"+
    "\3\0\1\47\7\0\1\50\1\51\5\0\1\44\23\0"+
    "\2\52\61\0\1\53\2\0\11\53\11\0\4\53\1\0"+
    "\2\53\1\0\3\53\1\0\1\53\1\0\1\53\21\0"+
    "\1\54\1\55\1\0\16\54\2\0\1\54\1\56\4\54"+
    "\1\0\6\54\1\57\1\54\1\0\1\54\21\0\1\60"+
    "\1\55\1\0\16\60\2\0\6\60\1\0\6\60\1\0"+
    "\1\60\1\0\1\60\21\0\1\54\1\55\1\0\16\54"+
    "\2\0\1\54\1\56\4\54\1\0\5\54\1\61\1\57"+
    "\1\54\1\0\1\54\21\0\1\62\2\0\7\62\1\0"+
    "\1\62\11\0\4\62\1\0\2\62\1\0\3\62\1\0"+
    "\1\62\1\0\1\62\21\0\1\54\1\55\1\0\16\54"+
    "\2\0\1\54\1\56\4\54\1\0\5\54\1\63\1\57"+
    "\1\54\1\0\1\54\70\0\1\64\2\0\1\65\7\0"+
    "\1\36\1\37\1\40\64\0\1\40\135\0\1\66\1\0"+
    "\1\65\20\0\1\44\4\0\1\44\21\0\1\44\5\0"+
    "\1\44\35\0\5\67\2\0\1\70\10\0\1\67\5\0"+
    "\1\70\36\0\5\71\13\0\1\71\44\0\5\72\13\0"+
    "\1\72\36\0\1\44\2\0\1\45\1\0\1\44\5\50"+
    "\3\0\1\47\7\0\1\50\1\44\5\0\1\44\26\0"+
    "\1\73\1\44\1\0\2\73\1\0\6\73\6\0\1\73"+
    "\4\0\1\73\1\44\3\0\1\73\1\0\1\44\25\0"+
    "\1\74\60\0\2\75\1\0\16\75\4\0\4\75\1\0"+
    "\6\75\1\0\1\75\1\0\1\75\21\0\1\76\2\0"+
    "\16\76\2\0\6\76\1\0\6\76\1\0\1\76\1\0"+
    "\1\76\21\0\1\54\1\55\1\0\6\54\1\77\7\54"+
    "\2\0\1\54\1\56\1\54\1\100\1\101\1\54\1\0"+
    "\1\54\1\77\1\54\1\102\2\54\1\57\1\54\1\0"+
    "\1\54\21\0\1\103\2\0\7\103\1\0\1\103\11\0"+
    "\4\103\1\0\2\103\1\0\3\103\1\0\1\103\1\0"+
    "\1\103\21\0\1\54\1\55\1\0\16\54\2\0\1\54"+
    "\1\56\4\54\1\0\5\54\1\104\1\57\1\54\1\0"+
    "\1\54\21\0\1\62\2\0\16\62\2\0\6\62\1\0"+
    "\6\62\1\57\1\62\1\0\1\62\21\0\1\54\1\55"+
    "\1\0\16\54\2\0\1\54\1\56\3\54\1\105\1\0"+
    "\6\54\1\57\1\54\1\0\1\54\27\0\1\44\4\0"+
    "\1\44\5\67\13\0\1\67\1\44\5\0\1\44\35\0"+
    "\5\67\13\0\1\67\36\0\1\44\2\0\1\45\1\0"+
    "\1\44\5\72\13\0\1\72\1\44\5\0\1\44\26\0"+
    "\1\73\1\44\1\0\1\73\1\106\1\0\6\73\6\0"+
    "\1\73\4\0\1\73\1\44\3\0\1\73\1\0\1\44"+
    "\26\0\1\107\57\0\1\76\2\0\16\76\2\0\1\76"+
    "\1\110\4\76\1\0\6\76\1\0\1\76\1\0\1\76"+
    "\21\0\1\54\1\55\1\0\16\54\2\0\1\54\1\56"+
    "\1\111\3\54\1\0\6\54\1\57\1\54\1\0\1\54"+
    "\21\0\1\54\1\55\1\0\16\54\2\0\1\54\1\56"+
    "\1\111\3\54\1\0\5\54\1\102\1\57\1\54\1\0"+
    "\1\54\21\0\1\54\1\55\1\0\16\54\2\0\1\54"+
    "\1\56\3\54\1\112\1\113\1\114\5\54\1\57\1\54"+
    "\1\0\1\54\21\0\1\54\1\55\1\0\16\54\2\0"+
    "\1\54\1\56\4\54\1\0\4\54\1\111\1\54\1\57"+
    "\1\54\1\0\1\54\21\0\1\115\2\0\7\115\1\103"+
    "\6\115\2\0\2\103\4\115\1\0\6\115\1\0\1\115"+
    "\1\0\1\115\21\0\1\54\1\55\1\0\16\54\2\0"+
    "\1\54\1\56\3\54\1\116\1\0\6\54\1\57\1\54"+
    "\1\0\1\54\21\0\1\54\1\55\1\0\16\54\2\0"+
    "\1\54\1\56\4\54\1\0\6\54\1\57\1\54\1\0"+
    "\1\54\14\0\1\117\11\0\1\73\1\44\1\0\1\73"+
    "\1\106\1\0\6\73\2\0\1\70\3\0\1\73\4\0"+
    "\1\73\1\44\3\0\1\73\1\70\1\44\27\0\1\120"+
    "\56\0\1\121\2\0\16\121\2\0\6\121\1\0\6\121"+
    "\1\0\1\121\1\0\1\121\21\0\1\54\1\55\1\0"+
    "\3\54\1\122\12\54\2\0\1\54\1\56\4\54\1\0"+
    "\6\54\1\57\1\54\1\0\1\54\21\0\1\54\1\55"+
    "\1\0\16\54\2\0\1\54\1\56\3\54\1\122\1\0"+
    "\6\54\1\57\1\54\1\0\1\54\25\0\1\123\60\0"+
    "\1\54\1\55\1\0\1\54\1\124\14\54\2\0\1\54"+
    "\1\56\4\54\1\0\6\54\1\57\1\54\1\0\1\54"+
    "\21\0\1\115\2\0\7\115\1\103\6\115\2\0\2\103"+
    "\4\115\1\0\6\115\1\57\1\115\1\0\1\115\21\0"+
    "\1\54\1\55\1\0\16\54\2\0\1\54\1\56\4\54"+
    "\1\125\1\105\5\54\1\57\1\54\1\0\1\54\14\0"+
    "\1\117\44\0\1\126\33\0\1\127\111\0\1\130\30\0"+
    "\1\54\1\55\1\0\16\54\2\0\1\54\1\56\4\54"+
    "\1\0\2\54\1\122\3\54\1\57\1\54\1\0\1\54"+
    "\101\0\1\117\44\0\1\131\34\0\1\132\54\0\2\133"+
    "\1\0\16\133\1\0\7\133\1\0\13\133\4\0\3\133"+
    "\4\0\1\133\15\0\1\134\53\0\1\135\1\133\1\0"+
    "\7\135\1\133\6\135\1\0\3\133\4\135\1\0\10\135"+
    "\1\133\1\135\1\133\4\0\3\133\4\0\1\133\16\0"+
    "\1\136\32\0\1\137\25\0\1\140\56\0\1\141\2\0"+
    "\7\141\1\0\1\141\11\0\4\141\1\0\2\141\1\0"+
    "\3\141\1\142\1\141\1\0\1\141\23\0\2\143\61\0"+
    "\1\141\2\0\16\141\2\0\1\141\1\144\4\141\1\0"+
    "\6\141\1\145\1\141\1\0\1\141\21\0\1\146\2\0"+
    "\7\146\1\0\1\146\11\0\4\146\1\0\2\146\1\0"+
    "\3\146\1\0\1\146\1\0\1\146\34\0\1\147\51\0"+
    "\1\141\2\0\6\141\1\150\7\141\2\0\1\141\1\144"+
    "\1\141\1\151\1\152\1\141\1\0\1\141\1\150\1\141"+
    "\1\153\2\141\1\145\1\141\1\0\1\141\21\0\1\154"+
    "\2\0\7\154\1\0\1\154\11\0\4\154\1\0\2\154"+
    "\1\0\3\154\1\0\1\154\1\0\1\154\21\0\1\146"+
    "\2\0\16\146\2\0\6\146\1\0\6\146\1\145\1\146"+
    "\1\0\1\146\66\0\1\137\17\0\1\141\2\0\16\141"+
    "\2\0\1\141\1\144\1\155\3\141\1\0\6\141\1\145"+
    "\1\141\1\0\1\141\21\0\1\141\2\0\16\141\2\0"+
    "\1\141\1\144\1\155\3\141\1\0\5\141\1\153\1\145"+
    "\1\141\1\0\1\141\21\0\1\141\2\0\16\141\2\0"+
    "\1\141\1\144\3\141\1\156\1\157\1\160\5\141\1\145"+
    "\1\141\1\0\1\141\21\0\1\141\2\0\16\141\2\0"+
    "\1\141\1\144\4\141\1\0\4\141\1\155\1\141\1\145"+
    "\1\141\1\0\1\141\21\0\1\161\2\0\7\161\1\154"+
    "\6\161\2\0\2\154\4\161\1\0\6\161\1\0\1\161"+
    "\1\0\1\161\21\0\1\141\2\0\3\141\1\162\12\141"+
    "\2\0\1\141\1\144\4\141\1\0\6\141\1\145\1\141"+
    "\1\0\1\141\21\0\1\141\2\0\16\141\2\0\1\141"+
    "\1\144\3\141\1\162\1\0\6\141\1\145\1\141\1\0"+
    "\1\141\25\0\1\163\60\0\1\141\2\0\1\141\1\164"+
    "\14\141\2\0\1\141\1\144\4\141\1\0\6\141\1\145"+
    "\1\141\1\0\1\141\21\0\1\161\2\0\7\161\1\154"+
    "\6\161\2\0\2\154\4\161\1\0\6\161\1\145\1\161"+
    "\1\0\1\161\2\0\1\165\16\0\1\141\2\0\16\141"+
    "\2\0\1\141\1\144\4\141\1\0\6\141\1\145\1\141"+
    "\1\0\1\141\2\0\1\165\52\0\1\166\11\0\1\165"+
    "\16\0\1\141\2\0\16\141\2\0\1\141\1\144\4\141"+
    "\1\0\2\141\1\162\3\141\1\145\1\141\1\0\1\141"+
    "\2\0\1\165\42\0\1\167\106\0\1\165\12\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5035];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\2\1\1\11\1\1\1\11\6\1\6\11"+
    "\5\1\1\11\3\1\2\11\3\1\3\0\2\1\12\0"+
    "\3\11\1\1\1\0\3\1\1\0\1\1\10\0\1\1"+
    "\6\0\1\1\3\0\4\1\3\0\1\11\4\0\1\1"+
    "\31\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  // TODO move this into an include file when bug #16053 is fixed
  @Override
  protected int getLineNumber() { return yyline; }
  @Override
  protected void setLineNumber(int x) { yyline = x; }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ErlangXref(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 238) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { writeUnicodeChar(yycharat(0));
            }
          case 25: break;
          case 2: 
            { out.write(yytext());
            }
          case 26: break;
          case 3: 
            { startNewLine();
            }
          case 27: break;
          case 4: 
            { out.write(yycharat(0));
            }
          case 28: break;
          case 5: 
            { out.write("<span class=\"n\">"); out.write(yytext()); out.write("</span>");
            }
          case 29: break;
          case 6: 
            { yybegin(STRING);out.write("<span class=\"s\">\"");
            }
          case 30: break;
          case 7: 
            { yybegin(QATOM);out.write("<span class=\"s\">\'");
            }
          case 31: break;
          case 8: 
            { yybegin(COMMENT);out.write("<span class=\"c\">%");
            }
          case 32: break;
          case 9: 
            { out.write( "&amp;");
            }
          case 33: break;
          case 10: 
            { out.write( "&lt;");
            }
          case 34: break;
          case 11: 
            { out.write( "&gt;");
            }
          case 35: break;
          case 12: 
            { yybegin(YYINITIAL); out.write("\"</span>");
            }
          case 36: break;
          case 13: 
            { yybegin(YYINITIAL); out.write("</span>");
    startNewLine();
            }
          case 37: break;
          case 14: 
            { yybegin(YYINITIAL); out.write("\'</span>");
            }
          case 38: break;
          case 15: 
            { String id = yytext();
    writeSymbol(id, Consts.kwd, yyline);
            }
          case 39: break;
          case 16: 
            { out.write("\\\"");
            }
          case 40: break;
          case 17: 
            { out.write("\\\\");
            }
          case 41: break;
          case 18: 
            { out.write("\\\'");
            }
          case 42: break;
          case 19: 
            { // Macros
    out.write("<span class=\"xm\">"); out.write(yytext()); out.write("</span>");
            }
          case 43: break;
          case 20: 
            { out.write(Util.breadcrumbPath(urlPrefix+"path=",yytext(),'/'));
            }
          case 44: break;
          case 21: 
            { writeEMailAddress(yytext());
            }
          case 45: break;
          case 22: 
            { String path = yytext();
        out.write("<a href=\""+urlPrefix+"path=");
        out.write(path);
        appendProject();
        out.write("\">");
        out.write(path);
        out.write("</a>");
            }
          case 46: break;
          case 23: 
            { String url = yytext();
         out.write("<a href=\"");
         out.write(url);out.write("\">");
         out.write(url);out.write("</a>");
            }
          case 47: break;
          case 24: 
            { out.write("&lt;");
        String path = yytext();
        path = path.substring(1, path.length() - 1);
        out.write("<a href=\""+urlPrefix+"path=");
        out.write(path);
        appendProject();
        out.write("\">");
        out.write(path);
        out.write("</a>");
        out.write("&gt;");
            }
          case 48: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
