/* The following code was generated by JFlex 1.6.1 */

/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").  
 * You may not use this file except in compliance with the License.
 *
 * See LICENSE.txt included in this distribution for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at LICENSE.txt.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

/*
 * Copyright (c) 2006, 2010, Oracle and/or its affiliates. All rights reserved.
 */

/*
 * Cross reference a Java file
 */

package com.grantingersoll.opengrok.analysis.java;
import com.grantingersoll.opengrok.analysis.JFlexXref;
import java.io.IOException;
import java.io.Writer;
import java.io.Reader;
import com.grantingersoll.opengrok.web.Util;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/Users/grantingersoll/projects/OpenGrok/src/org/opensolaris/opengrok/analysis/java/JavaXref.lex</tt>
 */
public class JavaXref extends JFlexXref {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int COMMENT = 4;
  public static final int SCOMMENT = 6;
  public static final int QSTRING = 8;
  public static final int JAVADOC = 10;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5, 5
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\1\0\1\1\1\2\22\0\1\1\1\6\1\47"+
    "\1\54\2\6\1\53\1\50\2\54\1\51\1\41\1\6\1\10\1\11"+
    "\1\36\1\37\11\5\1\55\1\6\1\45\1\6\1\46\1\6\1\43"+
    "\1\13\1\40\1\31\1\35\1\20\1\33\1\4\1\34\1\23\1\12"+
    "\1\4\1\30\1\27\1\32\1\17\1\15\1\4\1\16\1\25\1\21"+
    "\1\42\1\14\1\44\1\26\2\4\1\54\1\52\2\54\1\7\1\54"+
    "\1\13\1\40\1\31\1\35\1\20\1\33\1\4\1\34\1\23\1\12"+
    "\1\4\1\30\1\27\1\32\1\17\1\15\1\4\1\16\1\25\1\21"+
    "\1\42\1\14\1\44\1\26\2\4\3\54\1\6\261\0\2\22\115\0"+
    "\1\24\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ufe90\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\6\0\1\1\1\2\2\3\1\4\1\5\2\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\5\4\1\6\1\13"+
    "\2\4\1\2\2\14\1\15\2\4\1\16\2\0\1\5"+
    "\1\17\1\20\14\0\1\21\1\22\1\23\1\0\1\24"+
    "\4\0\2\5\2\0\1\5\20\0\1\2\4\25\1\26"+
    "\1\5\26\0\1\27\3\0\3\25\16\0\1\30\3\0"+
    "\1\30\1\0\1\30\1\0\1\31\2\0\3\25\11\0"+
    "\1\32\3\0\3\25\5\0\1\25\1\0\1\25\2\0"+
    "\1\33\3\0\1\25\3\0\1\34\2\0\1\25\5\0"+
    "\1\34\4\0\1\34\3\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[199];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\270\0\346\0\u0114\0\u0142"+
    "\0\u0170\0\u0114\0\u019e\0\u01cc\0\u0114\0\u01fa\0\u0228\0\u0256"+
    "\0\u0114\0\u0114\0\u0114\0\u0114\0\u0284\0\u02b2\0\u02e0\0\u030e"+
    "\0\u033c\0\u0114\0\u036a\0\u0398\0\u03c6\0\u03f4\0\u0422\0\u0114"+
    "\0\u0450\0\u047e\0\u04ac\0\u019e\0\u04da\0\u0508\0\u0536\0\u0114"+
    "\0\u0564\0\u0592\0\u05c0\0\u05ee\0\u0284\0\u061c\0\u064a\0\u0678"+
    "\0\u02b2\0\u06a6\0\u06d4\0\u0702\0\u0730\0\u0114\0\u0114\0\u0114"+
    "\0\u075e\0\u0114\0\u078c\0\u07ba\0\u07e8\0\u0816\0\u0844\0\u0872"+
    "\0\u08a0\0\u08ce\0\u08fc\0\u092a\0\u0958\0\u0986\0\u09b4\0\u09e2"+
    "\0\u0a10\0\u0a3e\0\u0a6c\0\u0a9a\0\u0ac8\0\u0af6\0\u0b24\0\u0b52"+
    "\0\u0b80\0\u0bae\0\u0bdc\0\u0114\0\u078c\0\u0c0a\0\u0c38\0\u0c66"+
    "\0\u0114\0\u0c94\0\u0cc2\0\u0cf0\0\u0d1e\0\u0d4c\0\u0d7a\0\u0da8"+
    "\0\u0dd6\0\u0e04\0\u0e32\0\u0e60\0\u0e8e\0\u0ebc\0\u0eea\0\u0f18"+
    "\0\u0f46\0\u0f74\0\u0fa2\0\u0fd0\0\u0ffe\0\u102c\0\u105a\0\u1088"+
    "\0\u10b6\0\u10e4\0\u1112\0\u1140\0\u116e\0\u119c\0\u11ca\0\u11f8"+
    "\0\u1226\0\u1254\0\u1282\0\u12b0\0\u12de\0\u130c\0\u133a\0\u1368"+
    "\0\u1396\0\u13c4\0\u13f2\0\u1420\0\u144e\0\u0284\0\u147c\0\u14aa"+
    "\0\u14d8\0\u0114\0\u1506\0\u0fd0\0\u1534\0\u10e4\0\u1562\0\u1590"+
    "\0\u15be\0\u15ec\0\u161a\0\u1648\0\u1676\0\u16a4\0\u16d2\0\u1700"+
    "\0\u172e\0\u175c\0\u178a\0\u17b8\0\u0114\0\u17e6\0\u1814\0\u1842"+
    "\0\u1870\0\u189e\0\u18cc\0\u18fa\0\u1928\0\u1956\0\u1984\0\u19b2"+
    "\0\u19e0\0\u1a0e\0\u1a3c\0\u1a6a\0\u1a98\0\u1984\0\u1ac6\0\u1af4"+
    "\0\u1b22\0\u1b50\0\u1b7e\0\u1bac\0\u1bda\0\u1ac6\0\u1c08\0\u1c36"+
    "\0\u1c64\0\u1c92\0\u1cc0\0\u1cee\0\u1d1c\0\u1d4a\0\u1d78\0\u1da6"+
    "\0\u1dd4\0\u1e02\0\u1e30\0\u0114\0\u1e5e\0\u1e8c\0\u1eba";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[199];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\13"+
    "\2\15\10\13\1\7\1\13\1\7\11\13\1\16\1\17"+
    "\1\13\1\15\1\13\1\15\1\13\1\20\1\21\1\22"+
    "\1\23\2\15\1\24\2\15\1\7\1\10\1\11\1\12"+
    "\1\25\1\26\1\15\3\26\10\25\1\7\1\25\1\7"+
    "\6\25\1\27\1\30\1\25\1\31\1\26\1\25\1\15"+
    "\1\25\1\15\1\25\1\32\1\21\1\33\2\15\1\34"+
    "\1\24\2\15\1\7\1\10\1\11\1\12\1\25\1\26"+
    "\1\15\3\26\10\25\1\7\1\25\1\7\6\25\1\27"+
    "\1\30\1\25\1\31\1\26\1\25\1\15\1\25\1\15"+
    "\1\25\1\32\1\21\2\15\1\35\1\15\1\24\2\15"+
    "\1\7\1\36\1\37\1\40\1\25\1\26\1\15\3\26"+
    "\10\25\1\7\1\25\1\7\6\25\1\27\1\30\1\25"+
    "\1\31\1\26\1\25\1\15\1\25\1\15\1\25\1\32"+
    "\1\21\4\15\1\24\2\15\1\7\1\10\1\11\1\12"+
    "\1\25\1\26\1\15\3\26\10\25\1\7\1\25\1\7"+
    "\6\25\1\27\1\30\1\25\1\31\1\26\1\25\1\15"+
    "\1\25\1\15\1\25\1\32\1\21\1\15\1\41\1\15"+
    "\1\42\1\24\2\15\1\7\1\10\1\11\1\12\1\25"+
    "\1\26\1\15\3\26\10\25\1\7\1\25\1\7\6\25"+
    "\1\27\1\30\1\25\1\31\1\26\1\25\1\15\1\25"+
    "\1\43\1\25\1\32\1\21\2\15\1\35\1\15\1\24"+
    "\2\15\57\0\1\10\1\11\1\12\55\0\1\12\56\0"+
    "\2\44\1\0\1\44\2\0\10\44\1\0\1\44\1\0"+
    "\11\44\1\0\2\44\1\0\1\44\1\0\1\44\16\0"+
    "\1\14\3\0\1\45\6\0\1\46\7\0\1\47\2\0"+
    "\1\47\1\0\1\47\1\0\1\14\2\0\1\47\51\0"+
    "\1\50\12\0\1\51\11\0\1\14\3\0\1\45\6\0"+
    "\1\46\5\0\1\52\1\0\1\47\2\0\1\47\1\0"+
    "\1\47\1\0\1\14\2\0\1\47\17\0\1\53\5\0"+
    "\10\53\1\0\1\53\1\0\11\53\1\54\1\0\1\53"+
    "\1\0\1\53\1\0\1\53\15\0\2\55\1\0\2\55"+
    "\1\56\10\55\1\0\1\55\1\0\11\55\1\57\2\55"+
    "\1\0\1\55\1\60\1\55\15\0\2\61\1\0\13\61"+
    "\1\0\1\61\1\0\11\61\1\0\2\61\1\0\1\61"+
    "\1\60\1\61\15\0\2\55\1\0\2\55\1\56\7\55"+
    "\1\62\1\0\1\55\1\0\11\55\1\57\2\55\1\0"+
    "\1\55\1\60\1\55\15\0\2\55\1\0\2\55\1\56"+
    "\7\55\1\63\1\0\1\55\1\0\11\55\1\57\2\55"+
    "\1\0\1\55\1\60\1\55\15\0\1\64\5\0\10\64"+
    "\1\0\1\64\1\0\11\64\2\0\1\64\1\0\1\64"+
    "\1\0\1\64\12\0\1\65\123\0\1\66\2\0\1\67"+
    "\41\0\1\70\20\0\1\36\1\37\1\40\55\0\1\40"+
    "\53\0\1\71\124\0\1\72\1\0\1\67\7\0\1\73"+
    "\2\0\1\73\2\0\3\73\1\74\2\73\1\75\1\76"+
    "\1\0\1\73\1\0\11\73\2\0\1\73\1\0\1\73"+
    "\1\0\1\73\16\0\1\77\31\0\1\77\23\0\1\100"+
    "\2\0\1\101\26\0\1\100\1\0\1\101\44\0\1\47"+
    "\2\0\1\47\1\0\1\47\4\0\1\47\64\0\1\102"+
    "\11\0\1\103\5\0\1\103\4\0\1\103\10\0\1\103"+
    "\1\0\1\103\1\0\1\103\1\0\2\103\21\0\2\53"+
    "\1\0\2\53\1\104\10\53\1\0\1\53\1\0\11\53"+
    "\1\105\2\53\1\0\1\53\1\0\1\53\15\0\1\106"+
    "\5\0\10\106\1\0\1\106\1\0\11\106\2\0\1\106"+
    "\1\0\1\106\1\0\1\106\15\0\2\55\1\0\2\55"+
    "\1\56\1\107\2\55\1\110\3\55\1\111\1\112\1\113"+
    "\1\0\1\55\1\114\2\55\1\115\2\55\1\116\1\117"+
    "\1\57\2\55\1\0\1\55\1\60\1\55\15\0\1\120"+
    "\5\0\10\120\1\0\1\120\1\0\11\120\2\0\1\120"+
    "\1\0\1\120\1\0\1\120\15\0\2\121\1\0\13\121"+
    "\1\0\1\121\1\0\11\121\1\0\2\121\1\0\1\121"+
    "\1\0\1\121\15\0\2\55\1\0\2\55\1\56\3\55"+
    "\1\122\4\55\1\0\1\55\1\0\11\55\1\57\2\55"+
    "\1\0\1\55\1\60\1\55\15\0\2\55\1\0\2\55"+
    "\1\56\7\55\1\123\1\0\1\55\1\0\11\55\1\57"+
    "\2\55\1\0\1\55\1\60\1\55\15\0\2\64\1\0"+
    "\13\64\1\0\1\64\1\0\11\64\1\57\2\64\1\0"+
    "\1\64\1\0\1\64\12\0\1\65\45\0\1\124\7\0"+
    "\1\71\46\0\1\124\11\0\2\125\1\0\1\125\2\0"+
    "\10\125\1\0\1\125\1\0\11\125\1\0\2\125\1\0"+
    "\1\125\1\0\1\125\15\0\2\125\1\0\1\125\2\0"+
    "\1\125\1\126\6\125\1\0\1\125\1\0\11\125\1\0"+
    "\2\125\1\0\1\125\1\0\1\125\15\0\2\125\1\0"+
    "\1\125\2\0\10\125\1\0\1\125\1\0\1\125\1\127"+
    "\7\125\1\0\2\125\1\0\1\125\1\0\1\125\15\0"+
    "\2\125\1\0\1\125\2\0\10\125\1\0\1\125\1\0"+
    "\7\125\1\130\1\125\1\0\2\125\1\0\1\125\1\0"+
    "\1\125\16\0\1\77\12\0\1\46\7\0\1\47\2\0"+
    "\1\47\1\0\1\47\1\0\1\77\2\0\1\47\20\0"+
    "\1\100\22\0\1\47\2\0\1\47\1\0\1\47\1\0"+
    "\1\100\2\0\1\47\20\0\1\100\31\0\1\100\16\0"+
    "\36\131\1\0\17\131\5\0\1\103\5\0\1\103\4\0"+
    "\1\132\7\0\1\47\1\103\1\0\1\103\1\0\1\103"+
    "\1\0\2\103\1\0\1\47\17\0\2\53\1\0\2\53"+
    "\1\104\1\133\2\53\1\134\3\53\1\135\1\136\1\137"+
    "\1\0\1\53\1\140\2\53\1\141\2\53\1\142\1\143"+
    "\1\105\2\53\1\0\1\53\1\0\1\53\15\0\1\144"+
    "\5\0\10\144\1\0\1\144\1\0\11\144\2\0\1\144"+
    "\1\0\1\144\1\0\1\144\15\0\2\106\1\0\13\106"+
    "\1\0\1\106\1\0\11\106\1\105\2\106\1\0\1\106"+
    "\1\0\1\106\15\0\2\55\1\0\2\55\1\56\1\55"+
    "\1\145\6\55\1\0\1\55\1\0\5\55\1\146\3\55"+
    "\1\57\2\55\1\0\1\55\1\60\1\55\15\0\2\55"+
    "\1\0\2\55\1\56\1\55\1\147\2\55\1\150\3\55"+
    "\1\0\1\55\1\0\11\55\1\57\2\55\1\0\1\55"+
    "\1\60\1\55\15\0\2\55\1\0\2\55\1\56\10\55"+
    "\1\0\1\55\1\0\1\55\1\151\7\55\1\57\2\55"+
    "\1\0\1\55\1\60\1\55\43\0\1\152\27\0\2\55"+
    "\1\0\2\55\1\56\10\55\1\0\1\55\1\0\5\55"+
    "\1\153\3\55\1\57\2\55\1\0\1\55\1\60\1\55"+
    "\15\0\2\55\1\0\2\55\1\56\10\55\1\0\1\55"+
    "\1\0\2\55\1\154\6\55\1\57\2\55\1\0\1\55"+
    "\1\60\1\55\15\0\2\55\1\0\2\55\1\56\5\55"+
    "\1\155\2\55\1\0\1\55\1\0\11\55\1\57\2\55"+
    "\1\0\1\55\1\60\1\55\15\0\2\55\1\0\2\55"+
    "\1\56\7\55\1\156\1\0\1\55\1\0\11\55\1\57"+
    "\2\55\1\0\1\55\1\60\1\55\15\0\2\55\1\0"+
    "\2\55\1\56\10\55\1\157\1\160\1\0\11\55\1\57"+
    "\2\55\1\0\1\55\1\60\1\55\15\0\2\161\1\0"+
    "\3\120\10\161\1\0\1\161\1\0\11\161\1\0\2\161"+
    "\1\0\1\161\1\0\1\161\15\0\2\121\1\0\2\121"+
    "\1\162\10\121\1\0\1\121\1\0\11\121\1\0\2\121"+
    "\1\0\1\121\1\0\1\121\15\0\2\55\1\0\2\55"+
    "\1\56\10\55\1\0\1\55\1\0\11\55\1\57\2\55"+
    "\1\0\1\55\1\60\1\55\10\0\1\163\4\0\2\55"+
    "\1\0\2\55\1\56\3\55\1\164\4\55\1\0\1\55"+
    "\1\0\11\55\1\57\2\55\1\0\1\55\1\60\1\55"+
    "\15\0\2\125\1\0\1\125\2\0\4\125\1\165\3\125"+
    "\1\0\1\125\1\0\11\125\1\0\2\125\1\0\1\125"+
    "\1\0\1\125\15\0\2\125\1\0\1\125\2\0\10\125"+
    "\1\0\1\125\1\0\4\125\1\166\4\125\1\0\2\125"+
    "\1\0\1\125\1\0\1\125\15\0\2\125\1\0\1\125"+
    "\2\0\4\125\1\167\3\125\1\0\1\125\1\0\11\125"+
    "\1\0\2\125\1\0\1\125\1\0\1\125\16\0\1\103"+
    "\2\0\1\101\2\0\1\103\4\0\1\132\7\0\1\47"+
    "\1\103\1\0\1\103\1\0\1\103\1\0\2\103\1\101"+
    "\1\47\17\0\2\53\1\0\2\53\1\104\1\53\1\170"+
    "\6\53\1\0\1\53\1\0\5\53\1\171\3\53\1\105"+
    "\2\53\1\0\1\53\1\0\1\53\15\0\2\53\1\0"+
    "\2\53\1\104\1\53\1\172\2\53\1\173\3\53\1\0"+
    "\1\53\1\0\11\53\1\105\2\53\1\0\1\53\1\0"+
    "\1\53\15\0\2\53\1\0\2\53\1\104\10\53\1\0"+
    "\1\53\1\0\1\53\1\174\7\53\1\105\2\53\1\0"+
    "\1\53\1\0\1\53\43\0\1\175\27\0\2\53\1\0"+
    "\2\53\1\104\10\53\1\0\1\53\1\0\5\53\1\176"+
    "\3\53\1\105\2\53\1\0\1\53\1\0\1\53\15\0"+
    "\2\53\1\0\2\53\1\104\10\53\1\0\1\53\1\0"+
    "\2\53\1\177\6\53\1\105\2\53\1\0\1\53\1\0"+
    "\1\53\15\0\2\53\1\0\2\53\1\104\5\53\1\200"+
    "\2\53\1\0\1\53\1\0\11\53\1\105\2\53\1\0"+
    "\1\53\1\0\1\53\15\0\2\53\1\0\2\53\1\104"+
    "\7\53\1\201\1\0\1\53\1\0\11\53\1\105\2\53"+
    "\1\0\1\53\1\0\1\53\15\0\2\53\1\0\2\53"+
    "\1\104\10\53\1\202\1\203\1\0\11\53\1\105\2\53"+
    "\1\0\1\53\1\0\1\53\15\0\2\204\1\0\3\144"+
    "\10\204\1\0\1\204\1\0\11\204\1\0\2\204\1\0"+
    "\1\204\1\0\1\204\15\0\2\55\1\0\2\55\1\56"+
    "\2\55\1\205\5\55\1\0\1\55\1\0\10\55\1\206"+
    "\1\57\2\55\1\0\1\55\1\60\1\55\15\0\2\55"+
    "\1\0\2\55\1\56\10\55\1\0\1\55\1\0\3\55"+
    "\1\207\5\55\1\57\2\55\1\0\1\55\1\60\1\55"+
    "\15\0\2\55\1\0\2\55\1\56\7\55\1\210\1\0"+
    "\1\55\1\0\11\55\1\57\2\55\1\0\1\55\1\60"+
    "\1\55\15\0\2\55\1\0\2\55\1\56\5\55\1\211"+
    "\2\55\1\0\1\55\1\0\11\55\1\57\2\55\1\0"+
    "\1\55\1\60\1\55\15\0\2\55\1\0\2\55\1\56"+
    "\7\55\1\206\1\0\1\55\1\0\11\55\1\57\2\55"+
    "\1\0\1\55\1\60\1\55\33\0\2\212\36\0\2\55"+
    "\1\0\2\55\1\56\10\55\1\212\1\206\1\0\11\55"+
    "\1\57\2\55\1\0\1\55\1\60\1\55\15\0\2\55"+
    "\1\0\2\55\1\56\10\55\1\0\1\55\1\0\3\55"+
    "\1\206\5\55\1\57\2\55\1\0\1\55\1\60\1\55"+
    "\15\0\2\55\1\0\2\55\1\56\10\55\1\0\1\55"+
    "\1\0\5\55\1\213\3\55\1\57\2\55\1\0\1\55"+
    "\1\60\1\55\15\0\2\55\1\0\2\55\1\56\10\55"+
    "\1\0\1\55\1\0\2\55\1\214\6\55\1\57\2\55"+
    "\1\0\1\55\1\60\1\55\44\0\1\215\26\0\2\55"+
    "\1\0\2\55\1\56\10\55\1\0\1\55\1\0\6\55"+
    "\1\213\2\55\1\57\2\55\1\0\1\55\1\60\1\55"+
    "\15\0\2\161\1\0\3\120\10\161\1\0\1\161\1\0"+
    "\11\161\1\57\2\161\1\0\1\161\1\0\1\161\15\0"+
    "\2\216\1\0\13\216\1\0\1\216\1\0\11\216\1\0"+
    "\2\216\1\0\1\216\1\0\1\216\47\0\1\217\23\0"+
    "\2\55\1\0\2\55\1\56\10\55\1\0\1\55\1\220"+
    "\1\122\10\55\1\57\2\55\1\0\1\55\1\60\1\55"+
    "\10\0\1\163\4\0\2\125\1\0\1\125\2\0\1\125"+
    "\1\221\6\125\1\0\1\125\1\0\11\125\1\0\2\125"+
    "\1\0\1\125\1\0\1\125\15\0\2\125\1\0\1\125"+
    "\2\0\6\125\1\222\1\125\1\0\1\125\1\0\11\125"+
    "\1\0\2\125\1\0\1\125\1\0\1\125\15\0\2\125"+
    "\1\0\1\125\2\0\5\125\1\223\2\125\1\0\1\125"+
    "\1\0\11\125\1\0\2\125\1\0\1\125\1\0\1\125"+
    "\15\0\2\53\1\0\2\53\1\104\2\53\1\224\5\53"+
    "\1\0\1\53\1\0\10\53\1\225\1\105\2\53\1\0"+
    "\1\53\1\0\1\53\15\0\2\53\1\0\2\53\1\104"+
    "\10\53\1\0\1\53\1\0\3\53\1\226\5\53\1\105"+
    "\2\53\1\0\1\53\1\0\1\53\15\0\2\53\1\0"+
    "\2\53\1\104\7\53\1\227\1\0\1\53\1\0\11\53"+
    "\1\105\2\53\1\0\1\53\1\0\1\53\15\0\2\53"+
    "\1\0\2\53\1\104\5\53\1\230\2\53\1\0\1\53"+
    "\1\0\11\53\1\105\2\53\1\0\1\53\1\0\1\53"+
    "\15\0\2\53\1\0\2\53\1\104\7\53\1\225\1\0"+
    "\1\53\1\0\11\53\1\105\2\53\1\0\1\53\1\0"+
    "\1\53\33\0\2\231\36\0\2\53\1\0\2\53\1\104"+
    "\10\53\1\231\1\225\1\0\11\53\1\105\2\53\1\0"+
    "\1\53\1\0\1\53\15\0\2\53\1\0\2\53\1\104"+
    "\10\53\1\0\1\53\1\0\3\53\1\225\5\53\1\105"+
    "\2\53\1\0\1\53\1\0\1\53\15\0\2\53\1\0"+
    "\2\53\1\104\10\53\1\0\1\53\1\0\5\53\1\232"+
    "\3\53\1\105\2\53\1\0\1\53\1\0\1\53\15\0"+
    "\2\53\1\0\2\53\1\104\10\53\1\0\1\53\1\0"+
    "\2\53\1\233\6\53\1\105\2\53\1\0\1\53\1\0"+
    "\1\53\44\0\1\234\26\0\2\53\1\0\2\53\1\104"+
    "\10\53\1\0\1\53\1\0\6\53\1\232\2\53\1\105"+
    "\2\53\1\0\1\53\1\0\1\53\15\0\2\204\1\0"+
    "\3\144\10\204\1\0\1\204\1\0\11\204\1\105\2\204"+
    "\1\0\1\204\1\0\1\204\1\0\1\235\13\0\2\55"+
    "\1\0\2\55\1\56\1\55\1\206\6\55\1\0\1\55"+
    "\1\0\11\55\1\57\2\55\1\0\1\55\1\60\1\55"+
    "\15\0\2\55\1\0\2\55\1\56\3\55\1\206\4\55"+
    "\1\0\1\55\1\0\11\55\1\57\2\55\1\0\1\55"+
    "\1\60\1\55\15\0\2\55\1\0\2\55\1\56\10\55"+
    "\1\0\1\55\1\0\4\55\1\236\4\55\1\57\2\55"+
    "\1\0\1\55\1\60\1\55\15\0\2\55\1\0\2\55"+
    "\1\56\3\55\1\237\4\55\1\0\1\55\1\0\11\55"+
    "\1\57\2\55\1\0\1\55\1\60\1\55\15\0\2\55"+
    "\1\0\2\55\1\56\10\55\1\0\1\55\1\0\6\55"+
    "\1\206\2\55\1\57\2\55\1\0\1\55\1\60\1\55"+
    "\44\0\1\212\60\0\1\240\74\0\1\163\4\0\2\125"+
    "\1\0\1\125\2\0\10\125\1\0\1\125\1\0\2\125"+
    "\1\241\6\125\1\0\2\125\1\0\1\125\1\0\1\125"+
    "\15\0\2\125\1\0\1\125\2\0\3\125\1\242\4\125"+
    "\1\0\1\125\1\0\11\125\1\0\2\125\1\0\1\125"+
    "\1\0\1\125\15\0\2\125\1\0\1\125\2\0\10\125"+
    "\1\0\1\125\1\0\11\125\1\0\2\125\1\0\1\125"+
    "\1\0\1\243\15\0\2\53\1\0\2\53\1\104\1\53"+
    "\1\225\6\53\1\0\1\53\1\0\11\53\1\105\2\53"+
    "\1\0\1\53\1\0\1\53\15\0\2\53\1\0\2\53"+
    "\1\104\10\53\1\0\1\53\1\0\11\53\1\105\2\53"+
    "\1\0\1\53\1\0\1\53\1\0\1\235\13\0\2\53"+
    "\1\0\2\53\1\104\3\53\1\225\4\53\1\0\1\53"+
    "\1\0\11\53\1\105\2\53\1\0\1\53\1\0\1\53"+
    "\15\0\2\53\1\0\2\53\1\104\10\53\1\0\1\53"+
    "\1\0\4\53\1\244\4\53\1\105\2\53\1\0\1\53"+
    "\1\0\1\53\15\0\2\53\1\0\2\53\1\104\3\53"+
    "\1\245\4\53\1\0\1\53\1\0\11\53\1\105\2\53"+
    "\1\0\1\53\1\0\1\53\57\0\1\235\13\0\2\53"+
    "\1\0\2\53\1\104\10\53\1\0\1\53\1\0\6\53"+
    "\1\225\2\53\1\105\2\53\1\0\1\53\1\0\1\53"+
    "\15\0\2\53\1\0\2\53\1\104\10\53\1\0\1\53"+
    "\1\0\3\53\1\225\5\53\1\105\2\53\1\0\1\53"+
    "\1\0\1\53\1\0\1\235\42\0\1\231\26\0\2\55"+
    "\1\0\2\55\1\56\10\55\1\0\1\55\1\0\7\55"+
    "\1\206\1\55\1\57\2\55\1\0\1\55\1\60\1\55"+
    "\15\0\2\55\1\0\2\55\1\56\6\55\1\246\1\55"+
    "\1\0\1\55\1\212\1\206\10\55\1\57\2\55\1\0"+
    "\1\55\1\60\1\55\15\0\16\247\1\0\1\247\1\0"+
    "\20\247\4\0\3\247\1\0\1\247\1\0\1\250\2\0"+
    "\2\125\1\0\1\125\2\0\10\125\1\0\1\125\1\0"+
    "\11\125\1\0\2\125\1\0\1\125\1\0\1\125\15\0"+
    "\2\125\1\0\1\125\2\0\7\125\1\251\1\0\1\125"+
    "\1\0\11\125\1\0\2\125\1\0\1\125\1\0\1\125"+
    "\15\0\2\125\1\0\1\125\2\0\10\125\1\0\1\125"+
    "\1\252\1\253\10\125\1\0\2\125\1\0\1\125\1\0"+
    "\1\125\15\0\2\53\1\0\2\53\1\104\10\53\1\0"+
    "\1\53\1\0\7\53\1\225\1\53\1\105\2\53\1\0"+
    "\1\53\1\0\1\53\15\0\2\53\1\0\2\53\1\104"+
    "\6\53\1\254\1\53\1\0\1\53\1\231\1\225\10\53"+
    "\1\105\2\53\1\0\1\53\1\0\1\53\15\0\2\55"+
    "\1\0\2\55\1\56\4\55\1\255\3\55\1\0\1\55"+
    "\1\0\11\55\1\57\2\55\1\0\1\55\1\60\1\55"+
    "\15\0\2\256\4\247\10\256\1\0\1\256\1\0\14\256"+
    "\1\247\1\256\1\247\1\256\4\0\3\247\1\0\1\247"+
    "\1\0\1\250\2\0\1\257\2\0\1\257\2\0\10\257"+
    "\1\0\1\257\1\0\11\257\2\0\1\257\1\0\1\257"+
    "\1\0\1\257\1\260\14\0\2\125\1\0\1\125\2\0"+
    "\10\125\1\261\1\262\1\0\11\125\1\0\2\125\1\0"+
    "\1\125\1\0\1\125\12\0\1\263\55\0\1\263\2\0"+
    "\2\125\1\0\1\125\2\0\10\125\1\0\1\125\1\0"+
    "\11\125\1\0\2\125\1\0\1\125\1\0\1\125\15\0"+
    "\2\53\1\0\2\53\1\104\4\53\1\264\3\53\1\0"+
    "\1\53\1\0\11\53\1\105\2\53\1\0\1\53\1\0"+
    "\1\53\15\0\2\55\1\0\2\55\1\56\7\55\1\265"+
    "\1\0\1\55\1\0\11\55\1\57\2\55\1\0\1\55"+
    "\1\60\1\55\15\0\2\266\1\0\1\266\2\0\10\266"+
    "\1\0\1\266\1\0\11\266\1\0\2\266\1\0\1\266"+
    "\1\0\1\266\15\0\1\267\2\0\1\267\2\0\10\267"+
    "\1\0\1\267\1\0\11\267\2\0\1\267\1\0\1\267"+
    "\1\0\1\267\30\0\1\270\42\0\2\125\1\0\1\125"+
    "\2\0\5\125\1\271\2\125\1\0\1\125\1\0\11\125"+
    "\1\0\2\125\1\0\1\125\1\0\1\125\12\0\1\263"+
    "\2\0\1\272\2\0\1\272\2\0\10\272\1\0\1\272"+
    "\1\0\11\272\2\0\1\272\1\0\1\272\1\0\1\272"+
    "\15\0\2\53\1\0\2\53\1\104\7\53\1\273\1\0"+
    "\1\53\1\0\11\53\1\105\2\53\1\0\1\53\1\0"+
    "\1\53\15\0\2\55\1\0\2\55\1\56\10\55\1\274"+
    "\1\275\1\0\11\55\1\57\2\55\1\0\1\55\1\60"+
    "\1\55\15\0\2\276\1\0\1\276\2\0\10\276\1\0"+
    "\1\276\1\0\11\276\1\0\2\276\1\0\1\276\1\0"+
    "\1\276\43\0\1\252\27\0\2\125\1\0\1\125\2\0"+
    "\10\125\1\0\1\125\1\0\5\125\1\253\3\125\1\0"+
    "\2\125\1\0\1\125\1\0\1\125\15\0\2\277\1\0"+
    "\1\277\2\0\10\277\1\0\1\277\1\0\11\277\1\0"+
    "\2\277\1\0\1\277\1\0\1\277\15\0\2\53\1\0"+
    "\2\53\1\104\10\53\1\300\1\301\1\0\11\53\1\105"+
    "\2\53\1\0\1\53\1\0\1\53\31\0\1\302\41\0"+
    "\2\55\1\0\2\55\1\56\6\55\1\303\1\55\1\0"+
    "\1\55\1\0\11\55\1\57\2\55\1\0\1\55\1\60"+
    "\1\55\15\0\2\276\1\0\1\276\2\0\10\276\1\0"+
    "\1\276\1\0\11\276\1\0\2\276\1\0\1\276\1\0"+
    "\1\276\1\0\1\304\13\0\2\277\1\0\1\277\1\0"+
    "\1\305\10\277\1\0\1\277\1\0\11\277\1\0\2\277"+
    "\1\0\1\277\1\0\1\277\31\0\1\306\41\0\2\53"+
    "\1\0\2\53\1\104\6\53\1\307\1\53\1\0\1\53"+
    "\1\0\11\53\1\105\2\53\1\0\1\53\1\0\1\53"+
    "\35\0\2\212\34\0\2\55\1\0\2\55\1\56\10\55"+
    "\1\0\1\55\1\212\1\206\10\55\1\57\2\55\1\0"+
    "\1\55\1\60\1\55\15\0\1\272\2\0\1\272\2\0"+
    "\10\272\1\0\1\272\1\0\11\272\2\0\1\272\1\0"+
    "\1\272\1\0\1\272\35\0\2\231\34\0\2\53\1\0"+
    "\2\53\1\104\10\53\1\0\1\53\1\231\1\225\10\53"+
    "\1\105\2\53\1\0\1\53\1\0\1\53\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7912];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\6\0\1\11\2\1\1\11\2\1\1\11\3\1\4\11"+
    "\5\1\1\11\5\1\1\11\4\1\2\0\1\1\1\11"+
    "\1\1\14\0\3\11\1\0\1\11\4\0\2\1\2\0"+
    "\1\1\20\0\1\11\4\1\1\11\1\1\26\0\1\1"+
    "\3\0\3\1\16\0\1\1\3\0\1\11\1\0\1\1"+
    "\1\0\1\1\2\0\3\1\11\0\1\11\3\0\3\1"+
    "\5\0\1\1\1\0\1\1\2\0\1\1\3\0\1\1"+
    "\3\0\1\1\2\0\1\1\5\0\1\1\4\0\1\11"+
    "\3\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[199];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  /* Must match WhiteSpace regex */
  private final static String WHITE_SPACE = "[ \t\f\r]+";

  // TODO move this into an include file when bug #16053 is fixed
  @Override
  protected int getLineNumber() { return yyline; }
  @Override
  protected void setLineNumber(int x) { yyline = x; }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public JavaXref(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 216) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { writeUnicodeChar(yycharat(0));
            }
          case 29: break;
          case 2: 
            { out.write(yytext());
            }
          case 30: break;
          case 3: 
            { startNewLine();
            }
          case 31: break;
          case 4: 
            { out.write(yycharat(0));
            }
          case 32: break;
          case 5: 
            { out.write("<span class=\"n\">"); out.write(yytext()); out.write("</span>");
            }
          case 33: break;
          case 6: 
            { out.write( "&lt;");
            }
          case 34: break;
          case 7: 
            { out.write( "&gt;");
            }
          case 35: break;
          case 8: 
            { yybegin(STRING);out.write("<span class=\"s\">\"");
            }
          case 36: break;
          case 9: 
            { yybegin(QSTRING);out.write("<span class=\"s\">\'");
            }
          case 37: break;
          case 10: 
            { out.write( "&amp;");
            }
          case 38: break;
          case 11: 
            { yybegin(YYINITIAL); out.write("\"</span>");
            }
          case 39: break;
          case 12: 
            { yybegin(YYINITIAL); out.write("</span>");
    startNewLine();
            }
          case 40: break;
          case 13: 
            { yybegin(YYINITIAL); out.write("'</span>");
            }
          case 41: break;
          case 14: 
            { String id = yytext();
    writeSymbol(id, Consts.kwd, yyline);
            }
          case 42: break;
          case 15: 
            { yybegin(SCOMMENT);out.write("<span class=\"c\">//");
            }
          case 43: break;
          case 16: 
            { yybegin(COMMENT);out.write("<span class=\"c\">/*");
            }
          case 44: break;
          case 17: 
            { out.write("\\\"");
            }
          case 45: break;
          case 18: 
            { out.write("\\\\");
            }
          case 46: break;
          case 19: 
            { yybegin(YYINITIAL); out.write("*/</span>");
            }
          case 47: break;
          case 20: 
            { out.write("\\\'");
            }
          case 48: break;
          case 21: 
            { out.append("<strong>").append(yytext()).append("</strong>");
            }
          case 49: break;
          case 22: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 3);
            { yybegin(JAVADOC);out.write("<span class=\"c\">/**");
            }
          case 50: break;
          case 23: 
            { out.write(Util.breadcrumbPath(urlPrefix+"path=",yytext(),'/'));
            }
          case 51: break;
          case 24: 
            { String path = yytext();
        out.write("<a href=\""+urlPrefix+"path=");
        out.write(path);
        appendProject();
        out.write("\">");
        out.write(path);
        out.write("</a>");
            }
          case 52: break;
          case 25: 
            { writeEMailAddress(yytext());
            }
          case 53: break;
          case 26: 
            { out.write("&lt;");
        String path = yytext();
        path = path.substring(1, path.length() - 1);
        out.write("<a href=\""+urlPrefix+"path=");
        out.write(path);
        appendProject();
        out.write("\">");
        out.write(path);
        out.write("</a>");
        out.write("&gt;");
            }
          case 54: break;
          case 27: 
            { String url = yytext();
         out.write("<a href=\"");
         out.write(url);out.write("\">");
         out.write(url);out.write("</a>");
            }
          case 55: break;
          case 28: 
            { String text = yytext();
    String[] tokens = text.split(WHITE_SPACE, 2);
    out.append("<strong>").append(tokens[0]).append("</strong>")
      .append(text.substring(tokens[0].length(),
                             text.length() - tokens[1].length()))
      .append("<em>").append(tokens[1]).append("</em>");
            }
          case 56: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
