/* The following code was generated by JFlex 1.6.1 */

/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").  
 * You may not use this file except in compliance with the License.
 *
 * See LICENSE.txt included in this distribution for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at LICENSE.txt.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

/*
 * Copyright (c) 2006, 2011, Oracle and/or its affiliates. All rights reserved.
 */

/*
 * Cross reference a Javascript file
 */

package com.grantingersoll.opengrok.analysis.javascript;
import com.grantingersoll.opengrok.analysis.JFlexXref;
import java.io.IOException;
import java.io.Writer;
import java.io.Reader;
import com.grantingersoll.opengrok.web.Util;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/Users/grantingersoll/projects/OpenGrok/src/com.grantingersoll.opengrok/analysis/javascript/JavaScriptXref.lex</tt>
 */
public class JavaScriptXref extends JFlexXref {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int COMMENT = 4;
  public static final int SCOMMENT = 6;
  public static final int QSTRING = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\1\0\1\1\1\2\22\0\1\1\1\6\1\45"+
    "\1\52\1\7\1\6\1\51\1\46\2\52\1\47\1\41\1\6\1\10"+
    "\1\12\1\36\1\37\11\5\1\53\1\6\1\43\1\6\1\44\1\6"+
    "\1\54\1\35\1\40\1\30\1\34\1\21\1\32\1\4\1\33\1\24"+
    "\1\13\1\4\1\27\1\26\1\31\1\20\1\16\1\4\1\17\1\15"+
    "\1\22\1\42\2\4\1\25\2\4\1\52\1\50\2\52\1\11\1\52"+
    "\1\35\1\40\1\30\1\34\1\21\1\32\1\4\1\33\1\24\1\13"+
    "\1\4\1\27\1\26\1\31\1\20\1\16\1\4\1\17\1\15\1\22"+
    "\1\42\2\4\1\25\2\4\3\52\1\6\261\0\2\23\115\0\1\14"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ufe90\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\2\3\1\4\1\5\2\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\5\4\1\6\1\13"+
    "\2\4\1\2\2\14\1\15\1\4\1\16\2\0\1\5"+
    "\1\17\1\20\14\0\1\21\1\22\1\23\1\0\1\24"+
    "\2\5\1\0\1\5\20\0\1\2\1\5\12\0\2\25"+
    "\12\0\1\26\23\0\1\25\1\0\1\27\2\0\1\30"+
    "\16\0\1\31\11\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\264\0\341\0\u010e\0\u013b"+
    "\0\341\0\u0168\0\u0195\0\341\0\u01c2\0\u01ef\0\u021c\0\341"+
    "\0\341\0\341\0\341\0\u0249\0\u0276\0\u02a3\0\u02d0\0\u02fd"+
    "\0\341\0\u032a\0\u0357\0\u0384\0\u03b1\0\u03de\0\341\0\u040b"+
    "\0\u0438\0\u0168\0\u0465\0\u0492\0\u04bf\0\341\0\341\0\u04ec"+
    "\0\u0519\0\u0546\0\u0249\0\u0573\0\u05a0\0\u05cd\0\u0276\0\u05fa"+
    "\0\u0627\0\u0654\0\u0681\0\341\0\341\0\341\0\u06ae\0\341"+
    "\0\u06db\0\u0708\0\u0735\0\u0762\0\u078f\0\u07bc\0\u07e9\0\u0816"+
    "\0\u0843\0\u0870\0\u089d\0\u08ca\0\u08f7\0\u0924\0\u0951\0\u097e"+
    "\0\u09ab\0\u09d8\0\u0a05\0\u0a32\0\341\0\u0a5f\0\u0a8c\0\u0ab9"+
    "\0\u0ae6\0\u0b13\0\u0b40\0\u0b6d\0\u0b9a\0\u0bc7\0\u0bf4\0\u0c21"+
    "\0\341\0\u0249\0\u0c4e\0\u0c7b\0\u0ca8\0\u0cd5\0\u0d02\0\u0d2f"+
    "\0\u0d5c\0\u0d89\0\u0db6\0\u0de3\0\u0e10\0\u0e3d\0\u0e6a\0\u0e97"+
    "\0\u0ec4\0\u0ef1\0\u0f1e\0\u0f4b\0\u0f78\0\u0fa5\0\u0fd2\0\u0fff"+
    "\0\u102c\0\u1059\0\u1086\0\u10b3\0\u10e0\0\u110d\0\u113a\0\u1167"+
    "\0\u0d2f\0\u1194\0\u0e3d\0\u11c1\0\u11ee\0\341\0\u121b\0\u1248"+
    "\0\u1275\0\u12a2\0\u12cf\0\u12fc\0\u1329\0\u1356\0\u1383\0\u13b0"+
    "\0\u13dd\0\u140a\0\u1437\0\u1464\0\u140a\0\u1491\0\u14be\0\u14eb"+
    "\0\u1518\0\u1545\0\u1572\0\u159f\0\u15cc\0\u15f9";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\12"+
    "\1\14\1\12\1\14\1\12\1\6\6\12\1\6\12\12"+
    "\1\15\1\16\1\12\1\14\1\12\1\17\1\20\1\21"+
    "\1\22\2\14\1\23\3\14\1\6\1\7\1\10\1\11"+
    "\1\24\1\25\2\14\3\25\1\24\1\6\6\24\1\6"+
    "\6\24\1\26\1\27\2\24\1\30\1\25\1\24\1\14"+
    "\1\24\1\31\1\20\1\32\2\14\1\33\1\23\3\14"+
    "\1\6\1\7\1\10\1\11\1\24\1\25\2\14\3\25"+
    "\1\24\1\6\6\24\1\6\6\24\1\26\1\27\2\24"+
    "\1\30\1\25\1\24\1\14\1\24\1\31\1\20\2\14"+
    "\1\34\1\14\1\23\3\14\1\6\1\35\1\36\1\37"+
    "\1\24\1\25\2\14\3\25\1\24\1\6\6\24\1\6"+
    "\6\24\1\26\1\27\2\24\1\30\1\25\1\24\1\14"+
    "\1\24\1\31\1\20\4\14\1\23\3\14\1\6\1\7"+
    "\1\10\1\11\1\24\1\25\2\14\3\25\1\24\1\6"+
    "\6\24\1\6\6\24\1\26\1\27\2\24\1\30\1\25"+
    "\1\24\1\14\1\24\1\31\1\20\1\14\1\40\1\14"+
    "\1\41\1\23\3\14\56\0\1\7\1\10\1\11\54\0"+
    "\1\11\55\0\2\42\1\0\1\42\1\0\1\42\1\0"+
    "\1\42\1\0\6\42\1\0\12\42\1\0\2\42\1\0"+
    "\1\42\17\0\1\13\4\0\1\43\6\0\1\44\5\0"+
    "\1\45\2\0\1\45\1\0\1\45\2\0\1\13\2\0"+
    "\1\45\50\0\1\46\10\0\1\47\12\0\1\13\4\0"+
    "\1\43\6\0\1\44\3\0\1\50\1\0\1\45\2\0"+
    "\1\45\1\0\1\45\2\0\1\13\2\0\1\45\16\0"+
    "\1\51\6\0\1\51\1\0\6\51\1\0\12\51\1\52"+
    "\1\0\1\51\1\0\1\51\16\0\2\53\2\0\2\53"+
    "\1\54\1\53\1\0\6\53\1\0\12\53\1\55\2\53"+
    "\1\0\1\53\11\0\1\56\4\0\2\57\2\0\4\57"+
    "\1\0\6\57\1\0\12\57\1\0\2\57\1\0\1\57"+
    "\11\0\1\56\4\0\2\53\2\0\2\53\1\54\1\53"+
    "\1\0\5\53\1\60\1\0\12\53\1\55\2\53\1\0"+
    "\1\53\11\0\1\56\4\0\2\53\2\0\2\53\1\54"+
    "\1\53\1\0\5\53\1\61\1\0\12\53\1\55\2\53"+
    "\1\0\1\53\11\0\1\56\4\0\1\62\6\0\1\62"+
    "\1\0\6\62\1\0\12\62\2\0\1\62\1\0\1\62"+
    "\13\0\1\63\120\0\1\64\2\0\1\65\42\0\1\66"+
    "\17\0\1\35\1\36\1\37\54\0\1\37\52\0\1\67"+
    "\121\0\1\70\1\0\1\65\11\0\1\71\31\0\1\71"+
    "\22\0\1\72\2\0\1\73\26\0\1\72\1\0\1\73"+
    "\42\0\1\45\2\0\1\45\1\0\1\45\5\0\1\45"+
    "\17\0\1\74\13\0\1\74\6\0\1\74\1\0\1\74"+
    "\1\0\2\74\1\0\2\74\20\0\2\51\2\0\2\51"+
    "\1\75\1\51\1\0\6\51\1\0\12\51\1\76\2\51"+
    "\1\0\1\51\16\0\1\77\6\0\1\77\1\0\6\77"+
    "\1\0\12\77\2\0\1\77\1\0\1\77\16\0\2\53"+
    "\2\0\2\53\1\54\1\100\1\0\1\53\1\101\3\53"+
    "\1\102\1\103\1\104\1\105\2\53\1\106\2\53\1\107"+
    "\1\110\1\53\1\55\2\53\1\0\1\53\11\0\1\56"+
    "\4\0\1\111\6\0\1\111\1\0\6\111\1\0\12\111"+
    "\2\0\1\111\1\0\1\111\16\0\2\112\2\0\4\112"+
    "\1\0\6\112\1\0\12\112\1\0\2\112\1\0\1\112"+
    "\16\0\2\53\2\0\2\53\1\54\1\53\1\0\1\53"+
    "\1\113\4\53\1\0\12\53\1\55\2\53\1\0\1\53"+
    "\11\0\1\56\4\0\2\53\2\0\2\53\1\54\1\53"+
    "\1\0\5\53\1\114\1\0\12\53\1\55\2\53\1\0"+
    "\1\53\11\0\1\56\4\0\2\62\2\0\4\62\1\0"+
    "\6\62\1\0\12\62\1\55\2\62\1\0\1\62\13\0"+
    "\1\63\43\0\1\115\10\0\1\67\44\0\1\115\13\0"+
    "\1\71\13\0\1\44\5\0\1\45\2\0\1\45\1\0"+
    "\1\45\2\0\1\71\2\0\1\45\17\0\1\72\21\0"+
    "\1\45\2\0\1\45\1\0\1\45\2\0\1\72\2\0"+
    "\1\45\17\0\1\72\31\0\1\72\22\0\1\74\13\0"+
    "\1\116\5\0\1\45\1\74\1\0\1\74\1\0\2\74"+
    "\1\0\2\74\1\0\1\45\16\0\2\51\2\0\2\51"+
    "\1\75\1\117\1\0\1\51\1\120\3\51\1\121\1\122"+
    "\1\123\1\124\2\51\1\125\2\51\1\126\1\127\1\51"+
    "\1\76\2\51\1\0\1\51\16\0\1\130\6\0\1\130"+
    "\1\0\6\130\1\0\12\130\2\0\1\130\1\0\1\130"+
    "\16\0\2\77\2\0\4\77\1\0\6\77\1\0\12\77"+
    "\1\76\2\77\1\0\1\77\16\0\2\53\2\0\2\53"+
    "\1\54\1\53\1\131\1\132\5\53\1\0\12\53\1\55"+
    "\2\53\1\0\1\53\11\0\1\56\4\0\2\53\2\0"+
    "\2\53\1\54\1\53\1\0\2\53\1\133\3\53\1\0"+
    "\11\53\1\134\1\55\2\53\1\0\1\53\11\0\1\56"+
    "\4\0\2\53\2\0\2\53\1\54\1\53\1\0\6\53"+
    "\1\0\1\53\1\135\10\53\1\55\2\53\1\0\1\53"+
    "\11\0\1\56\31\0\1\136\27\0\2\53\2\0\2\53"+
    "\1\54\1\53\1\0\6\53\1\0\5\53\1\137\4\53"+
    "\1\55\2\53\1\0\1\53\11\0\1\56\4\0\2\53"+
    "\2\0\2\53\1\54\1\53\1\0\6\53\1\0\2\53"+
    "\1\140\7\53\1\55\2\53\1\0\1\53\11\0\1\56"+
    "\4\0\2\53\2\0\2\53\1\54\1\53\1\0\3\53"+
    "\1\141\2\53\1\0\12\53\1\55\2\53\1\0\1\53"+
    "\11\0\1\56\4\0\2\53\2\0\2\53\1\54\1\53"+
    "\1\0\5\53\1\142\1\0\12\53\1\55\2\53\1\0"+
    "\1\53\11\0\1\56\4\0\2\53\2\0\2\53\1\54"+
    "\1\53\1\0\6\53\1\143\1\144\11\53\1\55\2\53"+
    "\1\0\1\53\11\0\1\56\4\0\2\145\2\0\3\111"+
    "\1\145\1\0\6\145\1\0\12\145\1\0\2\145\1\0"+
    "\1\145\16\0\2\112\2\0\2\112\1\146\1\112\1\0"+
    "\6\112\1\0\12\112\1\0\2\112\1\0\1\112\16\0"+
    "\2\53\2\0\2\53\1\54\1\53\1\0\6\53\1\0"+
    "\12\53\1\55\2\53\1\0\1\53\10\0\1\147\1\56"+
    "\4\0\2\53\2\0\2\53\1\54\1\53\1\0\1\53"+
    "\1\150\4\53\1\0\12\53\1\55\2\53\1\0\1\53"+
    "\11\0\1\56\5\0\1\74\2\0\1\73\10\0\1\116"+
    "\5\0\1\45\1\74\1\0\1\74\1\0\2\74\1\0"+
    "\2\74\1\73\1\45\16\0\2\51\2\0\2\51\1\75"+
    "\1\51\1\151\1\152\5\51\1\0\12\51\1\76\2\51"+
    "\1\0\1\51\16\0\2\51\2\0\2\51\1\75\1\51"+
    "\1\0\2\51\1\153\3\51\1\0\11\51\1\154\1\76"+
    "\2\51\1\0\1\51\16\0\2\51\2\0\2\51\1\75"+
    "\1\51\1\0\6\51\1\0\1\51\1\155\10\51\1\76"+
    "\2\51\1\0\1\51\43\0\1\156\27\0\2\51\2\0"+
    "\2\51\1\75\1\51\1\0\6\51\1\0\5\51\1\157"+
    "\4\51\1\76\2\51\1\0\1\51\16\0\2\51\2\0"+
    "\2\51\1\75\1\51\1\0\6\51\1\0\2\51\1\160"+
    "\7\51\1\76\2\51\1\0\1\51\16\0\2\51\2\0"+
    "\2\51\1\75\1\51\1\0\3\51\1\161\2\51\1\0"+
    "\12\51\1\76\2\51\1\0\1\51\16\0\2\51\2\0"+
    "\2\51\1\75\1\51\1\0\5\51\1\162\1\0\12\51"+
    "\1\76\2\51\1\0\1\51\16\0\2\51\2\0\2\51"+
    "\1\75\1\51\1\0\6\51\1\163\1\164\11\51\1\76"+
    "\2\51\1\0\1\51\16\0\2\165\2\0\3\130\1\165"+
    "\1\0\6\165\1\0\12\165\1\0\2\165\1\0\1\165"+
    "\16\0\2\53\2\0\2\53\1\54\1\53\1\0\3\53"+
    "\1\166\2\53\1\0\12\53\1\55\2\53\1\0\1\53"+
    "\11\0\1\56\4\0\2\53\2\0\2\53\1\54\1\53"+
    "\1\0\5\53\1\167\1\0\12\53\1\55\2\53\1\0"+
    "\1\53\11\0\1\56\4\0\2\53\2\0\2\53\1\54"+
    "\1\53\1\0\5\53\1\132\1\0\12\53\1\55\2\53"+
    "\1\0\1\53\11\0\1\56\23\0\2\131\34\0\2\53"+
    "\2\0\2\53\1\54\1\53\1\0\6\53\1\131\1\132"+
    "\11\53\1\55\2\53\1\0\1\53\11\0\1\56\4\0"+
    "\2\53\2\0\2\53\1\54\1\53\1\0\6\53\1\0"+
    "\3\53\1\132\6\53\1\55\2\53\1\0\1\53\11\0"+
    "\1\56\4\0\2\53\2\0\2\53\1\54\1\53\1\0"+
    "\6\53\1\0\5\53\1\170\4\53\1\55\2\53\1\0"+
    "\1\53\11\0\1\56\4\0\2\53\2\0\2\53\1\54"+
    "\1\53\1\0\6\53\1\0\2\53\1\171\7\53\1\55"+
    "\2\53\1\0\1\53\11\0\1\56\32\0\1\172\26\0"+
    "\2\53\2\0\2\53\1\54\1\53\1\0\6\53\1\0"+
    "\6\53\1\170\3\53\1\55\2\53\1\0\1\53\11\0"+
    "\1\56\4\0\2\145\2\0\3\111\1\145\1\0\6\145"+
    "\1\0\12\145\1\55\2\145\1\0\1\145\16\0\2\173"+
    "\2\0\4\173\1\0\6\173\1\0\12\173\1\0\2\173"+
    "\1\0\1\173\50\0\1\174\22\0\2\53\2\0\2\53"+
    "\1\54\1\53\1\175\1\113\5\53\1\0\12\53\1\55"+
    "\2\53\1\0\1\53\10\0\1\147\1\56\44\0\1\176"+
    "\14\0\2\51\2\0\2\51\1\75\1\51\1\0\6\51"+
    "\1\0\12\51\1\76\2\51\1\0\1\51\1\0\1\176"+
    "\14\0\2\51\2\0\2\51\1\75\1\51\1\0\3\51"+
    "\1\177\2\51\1\0\12\51\1\76\2\51\1\0\1\51"+
    "\16\0\2\51\2\0\2\51\1\75\1\51\1\0\5\51"+
    "\1\200\1\0\12\51\1\76\2\51\1\0\1\51\16\0"+
    "\2\51\2\0\2\51\1\75\1\51\1\0\5\51\1\152"+
    "\1\0\12\51\1\76\2\51\1\0\1\51\35\0\2\151"+
    "\34\0\2\51\2\0\2\51\1\75\1\51\1\0\6\51"+
    "\1\151\1\152\11\51\1\76\2\51\1\0\1\51\16\0"+
    "\2\51\2\0\2\51\1\75\1\51\1\0\6\51\1\0"+
    "\3\51\1\152\6\51\1\76\2\51\1\0\1\51\16\0"+
    "\2\51\2\0\2\51\1\75\1\51\1\0\6\51\1\0"+
    "\5\51\1\201\4\51\1\76\2\51\1\0\1\51\16\0"+
    "\2\51\2\0\2\51\1\75\1\51\1\0\6\51\1\0"+
    "\2\51\1\202\7\51\1\76\2\51\1\0\1\51\44\0"+
    "\1\203\26\0\2\51\2\0\2\51\1\75\1\51\1\0"+
    "\6\51\1\0\6\51\1\201\3\51\1\76\2\51\1\0"+
    "\1\51\16\0\2\165\2\0\3\130\1\165\1\0\6\165"+
    "\1\0\12\165\1\76\2\165\1\0\1\165\1\0\1\176"+
    "\14\0\2\53\2\0\2\53\1\54\1\53\1\0\1\53"+
    "\1\204\4\53\1\0\12\53\1\55\2\53\1\0\1\53"+
    "\11\0\1\56\4\0\2\53\2\0\2\53\1\54\1\53"+
    "\1\0\6\53\1\0\4\53\1\205\5\53\1\55\2\53"+
    "\1\0\1\53\11\0\1\56\4\0\2\53\2\0\2\53"+
    "\1\54\1\53\1\0\6\53\1\0\6\53\1\132\3\53"+
    "\1\55\2\53\1\0\1\53\11\0\1\56\32\0\1\131"+
    "\60\0\1\206\71\0\1\147\5\0\2\51\2\0\2\51"+
    "\1\75\1\51\1\0\1\51\1\207\4\51\1\0\12\51"+
    "\1\76\2\51\1\0\1\51\16\0\2\51\2\0\2\51"+
    "\1\75\1\51\1\0\6\51\1\0\4\51\1\210\5\51"+
    "\1\76\2\51\1\0\1\51\16\0\2\51\2\0\2\51"+
    "\1\75\1\51\1\0\6\51\1\0\6\51\1\152\3\51"+
    "\1\76\2\51\1\0\1\51\16\0\2\51\2\0\2\51"+
    "\1\75\1\51\1\0\6\51\1\0\3\51\1\152\6\51"+
    "\1\76\2\51\1\0\1\51\1\0\1\176\42\0\1\151"+
    "\26\0\2\53\2\0\2\53\1\54\1\53\1\131\1\132"+
    "\3\53\1\211\1\53\1\0\12\53\1\55\2\53\1\0"+
    "\1\53\11\0\1\56\4\0\2\53\2\0\2\53\1\54"+
    "\1\53\1\0\6\53\1\0\7\53\1\132\2\53\1\55"+
    "\2\53\1\0\1\53\11\0\1\56\4\0\10\212\1\0"+
    "\6\212\1\0\17\212\4\0\3\212\1\0\2\212\4\0"+
    "\2\51\2\0\2\51\1\75\1\51\1\151\1\152\3\51"+
    "\1\213\1\51\1\0\12\51\1\76\2\51\1\0\1\51"+
    "\16\0\2\51\2\0\2\51\1\75\1\51\1\0\6\51"+
    "\1\0\7\51\1\152\2\51\1\76\2\51\1\0\1\51"+
    "\16\0\2\53\2\0\2\53\1\54\1\53\1\0\2\53"+
    "\1\214\3\53\1\0\12\53\1\55\2\53\1\0\1\53"+
    "\11\0\1\56\4\0\2\215\5\212\1\215\1\0\6\215"+
    "\1\0\15\215\1\212\1\215\4\0\3\212\1\0\2\212"+
    "\4\0\2\51\2\0\2\51\1\75\1\51\1\0\2\51"+
    "\1\216\3\51\1\0\12\51\1\76\2\51\1\0\1\51"+
    "\16\0\2\53\2\0\2\53\1\54\1\53\1\0\5\53"+
    "\1\217\1\0\12\53\1\55\2\53\1\0\1\53\11\0"+
    "\1\56\4\0\2\51\2\0\2\51\1\75\1\51\1\0"+
    "\5\51\1\220\1\0\12\51\1\76\2\51\1\0\1\51"+
    "\16\0\2\53\2\0\2\53\1\54\1\53\1\0\6\53"+
    "\1\221\1\222\11\53\1\55\2\53\1\0\1\53\11\0"+
    "\1\56\4\0\2\51\2\0\2\51\1\75\1\51\1\0"+
    "\6\51\1\223\1\224\11\51\1\76\2\51\1\0\1\51"+
    "\33\0\1\225\37\0\2\53\2\0\2\53\1\54\1\53"+
    "\1\0\4\53\1\100\1\53\1\0\12\53\1\55\2\53"+
    "\1\0\1\53\11\0\1\56\21\0\1\226\37\0\2\51"+
    "\2\0\2\51\1\75\1\51\1\0\4\51\1\117\1\51"+
    "\1\0\12\51\1\76\2\51\1\0\1\51\26\0\2\131"+
    "\53\0\2\151\37\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5670];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\2\1\1\11\2\1\1\11\3\1\4\11"+
    "\5\1\1\11\5\1\1\11\3\1\2\0\1\1\2\11"+
    "\14\0\3\11\1\0\1\11\2\1\1\0\1\1\20\0"+
    "\1\11\1\1\12\0\1\11\1\1\12\0\1\1\23\0"+
    "\1\1\1\0\1\1\2\0\1\11\16\0\1\1\11\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[150];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  /* Must match WhiteSpace regex */
  private final static String WHITE_SPACE = "[ \t\f\r]+";

  // TODO move this into an include file when bug #16053 is fixed
  @Override
  protected int getLineNumber() { return yyline; }
  @Override
  protected void setLineNumber(int x) { yyline = x; }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public JavaScriptXref(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 214) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { writeUnicodeChar(yycharat(0));
            }
          case 26: break;
          case 2: 
            { out.write(yytext());
            }
          case 27: break;
          case 3: 
            { startNewLine();
            }
          case 28: break;
          case 4: 
            { out.write(yycharat(0));
            }
          case 29: break;
          case 5: 
            { out.write("<span class=\"n\">"); out.write(yytext()); out.write("</span>");
            }
          case 30: break;
          case 6: 
            { out.write( "&lt;");
            }
          case 31: break;
          case 7: 
            { out.write( "&gt;");
            }
          case 32: break;
          case 8: 
            { yybegin(STRING);out.write("<span class=\"s\">\"");
            }
          case 33: break;
          case 9: 
            { yybegin(QSTRING);out.write("<span class=\"s\">\'");
            }
          case 34: break;
          case 10: 
            { out.write( "&amp;");
            }
          case 35: break;
          case 11: 
            { yybegin(YYINITIAL); out.write("\"</span>");
            }
          case 36: break;
          case 12: 
            { yybegin(YYINITIAL); out.write("</span>");
    startNewLine();
            }
          case 37: break;
          case 13: 
            { yybegin(YYINITIAL); out.write("'</span>");
            }
          case 38: break;
          case 14: 
            { String id = yytext();
    writeSymbol(id, Consts.kwd, yyline);
            }
          case 39: break;
          case 15: 
            { yybegin(SCOMMENT);out.write("<span class=\"c\">//");
            }
          case 40: break;
          case 16: 
            { yybegin(COMMENT);out.write("<span class=\"c\">/*");
            }
          case 41: break;
          case 17: 
            { out.write("\\\"");
            }
          case 42: break;
          case 18: 
            { out.write("\\\\");
            }
          case 43: break;
          case 19: 
            { yybegin(YYINITIAL); out.write("*/</span>");
            }
          case 44: break;
          case 20: 
            { out.write("\\\'");
            }
          case 45: break;
          case 21: 
            { String path = yytext();
        out.write("<a href=\""+urlPrefix+"path=");
        out.write(path);
        appendProject();
        out.write("\">");
        out.write(path);
        out.write("</a>");
            }
          case 46: break;
          case 22: 
            { out.write(Util.breadcrumbPath(urlPrefix+"path=",yytext(),'/'));
            }
          case 47: break;
          case 23: 
            { writeEMailAddress(yytext());
            }
          case 48: break;
          case 24: 
            { out.write("&lt;");
        String path = yytext();
        path = path.substring(1, path.length() - 1);
        out.write("<a href=\""+urlPrefix+"path=");
        out.write(path);
        appendProject();
        out.write("\">");
        out.write(path);
        out.write("</a>");
        out.write("&gt;");
            }
          case 49: break;
          case 25: 
            { String url = yytext();
         out.write("<a href=\"");
         out.write(url);out.write("\">");
         out.write(url);out.write("</a>");
            }
          case 50: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
