/* The following code was generated by JFlex 1.6.1 */

/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").  
 * You may not use this file except in compliance with the License.
 *
 * See LICENSE.txt included in this distribution for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at LICENSE.txt.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

/*
 * Copyright (c) 2006, 2010, Oracle and/or its affiliates. All rights reserved.
 */

/*
 * Cross reference a Java file
 */

package com.grantingersoll.opengrok.analysis.scala;
import com.grantingersoll.opengrok.analysis.JFlexXref;
import java.io.IOException;
import java.io.Writer;
import java.io.Reader;
import com.grantingersoll.opengrok.web.Util;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/Users/grantingersoll/projects/OpenGrok/src/com.grantingersoll.opengrok/analysis/scala/ScalaXref.lex</tt>
 */
public class ScalaXref extends JFlexXref {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int COMMENT = 4;
  public static final int SCOMMENT = 6;
  public static final int QSTRING = 8;
  public static final int JAVADOC = 10;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5, 5
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\1\0\1\1\1\2\22\0\1\1\1\6\1\46"+
    "\1\53\2\6\1\52\1\47\2\53\1\50\1\40\1\6\1\10\1\11"+
    "\1\35\1\36\11\5\1\54\1\6\1\44\1\6\1\45\1\6\1\42"+
    "\1\15\1\37\1\14\1\34\1\22\1\31\1\4\1\32\1\25\1\33"+
    "\1\4\1\16\1\27\1\30\1\21\1\17\1\4\1\20\1\13\1\23"+
    "\1\41\1\4\1\43\1\26\2\4\1\53\1\51\2\53\1\7\1\53"+
    "\1\15\1\37\1\14\1\34\1\22\1\31\1\4\1\32\1\25\1\33"+
    "\1\4\1\16\1\27\1\30\1\21\1\17\1\4\1\20\1\13\1\23"+
    "\1\41\1\4\1\43\1\26\2\4\3\53\1\6\261\0\2\24\115\0"+
    "\1\12\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ufe90\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\6\0\1\1\1\2\2\3\1\4\1\5\2\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\5\4\1\6\1\13"+
    "\2\4\1\2\2\14\1\15\2\4\1\16\1\0\1\5"+
    "\1\0\1\17\1\20\14\0\1\21\1\22\1\23\1\0"+
    "\1\24\4\0\2\5\2\0\1\5\22\0\1\2\4\25"+
    "\1\26\1\5\32\0\1\27\3\0\3\25\24\0\3\30"+
    "\2\0\1\31\2\0\3\25\12\0\1\32\5\0\3\25"+
    "\7\0\1\25\1\0\1\25\2\0\1\33\3\0\1\25"+
    "\3\0\1\34\2\0\1\25\5\0\1\34\4\0\1\34"+
    "\3\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\264\0\341\0\u010e\0\u013b"+
    "\0\u0168\0\u010e\0\u0195\0\u01c2\0\u010e\0\u01ef\0\u021c\0\u0249"+
    "\0\u010e\0\u010e\0\u010e\0\u010e\0\u0276\0\u02a3\0\u02d0\0\u02fd"+
    "\0\u032a\0\u010e\0\u0357\0\u0384\0\u03b1\0\u03de\0\u040b\0\u010e"+
    "\0\u0438\0\u0465\0\u0492\0\u0195\0\u04bf\0\u04ec\0\u0519\0\u010e"+
    "\0\u0546\0\u0573\0\u05a0\0\u05cd\0\u0276\0\u05fa\0\u0627\0\u0654"+
    "\0\u02a3\0\u0681\0\u06ae\0\u06db\0\u0708\0\u010e\0\u010e\0\u010e"+
    "\0\u0735\0\u010e\0\u0762\0\u078f\0\u07bc\0\u07e9\0\u0816\0\u0843"+
    "\0\u0870\0\u089d\0\u08ca\0\u08f7\0\u0924\0\u0951\0\u097e\0\u09ab"+
    "\0\u09d8\0\u0a05\0\u0a32\0\u0a5f\0\u0a8c\0\u0ab9\0\u0ae6\0\u0b13"+
    "\0\u0b40\0\u0b6d\0\u0b9a\0\u0bc7\0\u0bf4\0\u010e\0\u0762\0\u0c21"+
    "\0\u0c4e\0\u0c7b\0\u010e\0\u0ca8\0\u0cd5\0\u0d02\0\u0d2f\0\u0d5c"+
    "\0\u0d89\0\u0db6\0\u0de3\0\u0e10\0\u0e3d\0\u0e6a\0\u0e97\0\u0ec4"+
    "\0\u0ef1\0\u0f1e\0\u0f4b\0\u0f78\0\u0fa5\0\u0fd2\0\u0fff\0\u102c"+
    "\0\u1059\0\u1086\0\u10b3\0\u10e0\0\u110d\0\u113a\0\u1167\0\u1194"+
    "\0\u11c1\0\u11ee\0\u121b\0\u1248\0\u1275\0\u12a2\0\u12cf\0\u12fc"+
    "\0\u1329\0\u1356\0\u1383\0\u13b0\0\u13dd\0\u140a\0\u1437\0\u1464"+
    "\0\u1491\0\u14be\0\u14eb\0\u1518\0\u1545\0\u1572\0\u159f\0\u15cc"+
    "\0\u15f9\0\u0276\0\u010e\0\u1059\0\u1626\0\u1653\0\u1194\0\u1680"+
    "\0\u16ad\0\u16da\0\u1707\0\u1734\0\u1761\0\u178e\0\u17bb\0\u17e8"+
    "\0\u1815\0\u1842\0\u186f\0\u189c\0\u18c9\0\u18f6\0\u010e\0\u1923"+
    "\0\u1950\0\u197d\0\u19aa\0\u19d7\0\u1a04\0\u1a31\0\u1a5e\0\u1a8b"+
    "\0\u1ab8\0\u1ae5\0\u1b12\0\u1b3f\0\u1b6c\0\u1b99\0\u1bc6\0\u1bf3"+
    "\0\u1c20\0\u1c4d\0\u1c7a\0\u1b6c\0\u1ca7\0\u1cd4\0\u1d01\0\u1d2e"+
    "\0\u1d5b\0\u1d88\0\u1db5\0\u1ca7\0\u1de2\0\u1e0f\0\u1e3c\0\u1e69"+
    "\0\u1e96\0\u1ec3\0\u1ef0\0\u1f1d\0\u1f4a\0\u1f77\0\u1fa4\0\u1fd1"+
    "\0\u1ffe\0\u010e\0\u202b\0\u2058\0\u2085";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\13"+
    "\2\15\1\7\11\13\1\7\10\13\1\16\1\17\1\13"+
    "\1\15\1\13\1\15\1\13\1\20\1\21\1\22\1\23"+
    "\2\15\1\24\2\15\1\7\1\10\1\11\1\12\1\25"+
    "\1\26\1\15\3\26\1\7\11\25\1\7\4\25\1\27"+
    "\1\30\2\25\1\31\1\26\1\25\1\15\1\25\1\15"+
    "\1\25\1\32\1\21\1\33\2\15\1\34\1\24\2\15"+
    "\1\7\1\10\1\11\1\12\1\25\1\26\1\15\3\26"+
    "\1\7\11\25\1\7\4\25\1\27\1\30\2\25\1\31"+
    "\1\26\1\25\1\15\1\25\1\15\1\25\1\32\1\21"+
    "\2\15\1\35\1\15\1\24\2\15\1\7\1\36\1\37"+
    "\1\40\1\25\1\26\1\15\3\26\1\7\11\25\1\7"+
    "\4\25\1\27\1\30\2\25\1\31\1\26\1\25\1\15"+
    "\1\25\1\15\1\25\1\32\1\21\4\15\1\24\2\15"+
    "\1\7\1\10\1\11\1\12\1\25\1\26\1\15\3\26"+
    "\1\7\11\25\1\7\4\25\1\27\1\30\2\25\1\31"+
    "\1\26\1\25\1\15\1\25\1\15\1\25\1\32\1\21"+
    "\1\15\1\41\1\15\1\42\1\24\2\15\1\7\1\10"+
    "\1\11\1\12\1\25\1\26\1\15\3\26\1\7\11\25"+
    "\1\7\4\25\1\27\1\30\2\25\1\31\1\26\1\25"+
    "\1\15\1\25\1\43\1\25\1\32\1\21\2\15\1\35"+
    "\1\15\1\24\2\15\56\0\1\10\1\11\1\12\54\0"+
    "\1\12\55\0\2\44\1\0\1\44\3\0\11\44\1\0"+
    "\10\44\1\0\2\44\1\0\1\44\1\0\1\44\16\0"+
    "\1\14\3\0\1\45\4\0\1\46\3\0\1\47\6\0"+
    "\1\46\2\0\1\46\1\0\1\14\2\0\1\46\50\0"+
    "\1\50\12\0\1\51\11\0\1\14\3\0\1\45\4\0"+
    "\1\46\3\0\1\47\3\0\1\52\2\0\1\46\2\0"+
    "\1\46\1\0\1\14\2\0\1\46\17\0\1\53\6\0"+
    "\11\53\1\0\10\53\1\54\1\0\1\53\1\0\1\53"+
    "\1\0\1\53\15\0\2\55\1\0\2\55\1\56\1\0"+
    "\11\55\1\0\10\55\1\57\2\55\1\0\1\55\1\60"+
    "\1\55\15\0\2\61\1\0\3\61\1\0\11\61\1\0"+
    "\10\61\1\0\2\61\1\0\1\61\1\60\1\61\15\0"+
    "\2\55\1\0\2\55\1\56\1\0\10\55\1\62\1\0"+
    "\10\55\1\57\2\55\1\0\1\55\1\60\1\55\15\0"+
    "\2\55\1\0\2\55\1\56\1\0\10\55\1\63\1\0"+
    "\10\55\1\57\2\55\1\0\1\55\1\60\1\55\15\0"+
    "\1\64\6\0\11\64\1\0\10\64\2\0\1\64\1\0"+
    "\1\64\1\0\1\64\12\0\1\65\121\0\1\66\2\0"+
    "\1\67\40\0\1\70\20\0\1\36\1\37\1\40\54\0"+
    "\1\40\52\0\1\71\122\0\1\72\1\0\1\67\7\0"+
    "\1\73\2\0\1\73\3\0\4\73\1\74\2\73\1\75"+
    "\1\76\1\0\10\73\2\0\1\73\1\0\1\73\1\0"+
    "\1\73\16\0\1\77\30\0\1\77\34\0\1\46\12\0"+
    "\1\46\2\0\1\46\4\0\1\46\20\0\1\100\2\0"+
    "\1\101\25\0\1\100\1\0\1\101\64\0\1\102\11\0"+
    "\1\103\6\0\2\103\4\0\1\103\6\0\1\103\2\0"+
    "\1\103\1\0\2\103\21\0\2\53\1\0\2\53\1\104"+
    "\1\0\11\53\1\0\10\53\1\105\2\53\1\0\1\53"+
    "\1\0\1\53\15\0\1\106\6\0\11\106\1\0\10\106"+
    "\2\0\1\106\1\0\1\106\1\0\1\106\15\0\2\55"+
    "\1\0\2\55\1\56\1\107\1\110\1\111\2\55\1\112"+
    "\3\55\1\113\1\114\1\115\1\116\3\55\1\117\1\120"+
    "\1\121\1\57\2\55\1\0\1\55\1\60\1\55\15\0"+
    "\1\122\6\0\11\122\1\0\10\122\2\0\1\122\1\0"+
    "\1\122\1\0\1\122\15\0\2\123\1\0\3\123\1\0"+
    "\11\123\1\0\10\123\1\0\2\123\1\0\1\123\1\0"+
    "\1\123\15\0\2\55\1\0\2\55\1\56\1\0\4\55"+
    "\1\124\4\55\1\0\10\55\1\57\2\55\1\0\1\55"+
    "\1\60\1\55\15\0\2\55\1\0\2\55\1\56\1\0"+
    "\10\55\1\125\1\0\10\55\1\57\2\55\1\0\1\55"+
    "\1\60\1\55\15\0\2\64\1\0\3\64\1\0\11\64"+
    "\1\0\10\64\1\57\2\64\1\0\1\64\1\0\1\64"+
    "\12\0\1\65\44\0\1\126\7\0\1\71\45\0\1\126"+
    "\11\0\2\127\1\0\1\127\3\0\11\127\1\0\10\127"+
    "\1\0\2\127\1\0\1\127\1\0\1\127\15\0\2\127"+
    "\1\0\1\127\3\0\2\127\1\130\6\127\1\0\10\127"+
    "\1\0\2\127\1\0\1\127\1\0\1\127\15\0\2\127"+
    "\1\0\1\127\3\0\11\127\1\0\1\127\1\131\6\127"+
    "\1\0\2\127\1\0\1\127\1\0\1\127\15\0\2\127"+
    "\1\0\1\127\3\0\11\127\1\0\5\127\1\132\2\127"+
    "\1\0\2\127\1\0\1\127\1\0\1\127\16\0\1\77"+
    "\10\0\1\46\3\0\1\47\6\0\1\46\2\0\1\46"+
    "\1\0\1\77\2\0\1\46\20\0\1\100\10\0\1\46"+
    "\12\0\1\46\2\0\1\46\1\0\1\100\2\0\1\46"+
    "\20\0\1\100\30\0\1\100\16\0\35\133\1\0\17\133"+
    "\5\0\1\103\6\0\2\103\1\46\3\0\1\134\6\0"+
    "\1\103\2\0\1\103\1\0\2\103\1\0\1\46\17\0"+
    "\2\53\1\0\2\53\1\104\1\135\1\136\1\137\2\53"+
    "\1\140\3\53\1\141\1\142\1\143\1\144\3\53\1\145"+
    "\1\146\1\147\1\105\2\53\1\0\1\53\1\0\1\53"+
    "\15\0\1\150\6\0\11\150\1\0\10\150\2\0\1\150"+
    "\1\0\1\150\1\0\1\150\15\0\2\106\1\0\3\106"+
    "\1\0\11\106\1\0\10\106\1\105\2\106\1\0\1\106"+
    "\1\0\1\106\25\0\1\151\44\0\2\55\1\0\2\55"+
    "\1\56\1\0\1\55\1\152\7\55\1\0\10\55\1\57"+
    "\2\55\1\0\1\55\1\60\1\55\15\0\2\55\1\0"+
    "\2\55\1\56\1\0\6\55\1\153\2\55\1\0\10\55"+
    "\1\57\2\55\1\0\1\55\1\60\1\55\15\0\2\55"+
    "\1\0\2\55\1\56\1\0\2\55\1\154\2\55\1\155"+
    "\3\55\1\0\10\55\1\57\2\55\1\0\1\55\1\60"+
    "\1\55\15\0\2\55\1\0\2\55\1\56\1\0\11\55"+
    "\1\0\1\55\1\156\6\55\1\57\2\55\1\0\1\55"+
    "\1\60\1\55\41\0\1\157\30\0\2\55\1\0\2\55"+
    "\1\56\1\0\11\55\1\0\3\55\1\160\4\55\1\57"+
    "\2\55\1\0\1\55\1\60\1\55\15\0\2\55\1\0"+
    "\2\55\1\56\1\0\11\55\1\0\2\55\1\161\5\55"+
    "\1\57\2\55\1\0\1\55\1\60\1\55\15\0\2\55"+
    "\1\0\2\55\1\56\1\0\10\55\1\162\1\0\10\55"+
    "\1\57\2\55\1\0\1\55\1\60\1\55\15\0\2\55"+
    "\1\0\2\55\1\56\1\0\2\55\1\163\6\55\1\0"+
    "\3\55\1\164\4\55\1\57\2\55\1\0\1\55\1\60"+
    "\1\55\15\0\2\55\1\0\2\55\1\56\1\0\11\55"+
    "\1\165\1\166\7\55\1\57\2\55\1\0\1\55\1\60"+
    "\1\55\15\0\2\167\1\0\3\122\1\0\11\167\1\0"+
    "\10\167\1\0\2\167\1\0\1\167\1\0\1\167\15\0"+
    "\2\123\1\0\2\123\1\170\1\0\11\123\1\0\10\123"+
    "\1\0\2\123\1\0\1\123\1\0\1\123\15\0\2\55"+
    "\1\0\2\55\1\56\1\0\11\55\1\0\10\55\1\57"+
    "\2\55\1\0\1\55\1\60\1\55\10\0\1\171\4\0"+
    "\2\55\1\0\2\55\1\56\1\0\4\55\1\172\4\55"+
    "\1\0\10\55\1\57\2\55\1\0\1\55\1\60\1\55"+
    "\15\0\2\127\1\0\1\127\3\0\5\127\1\173\3\127"+
    "\1\0\10\127\1\0\2\127\1\0\1\127\1\0\1\127"+
    "\15\0\2\127\1\0\1\127\3\0\1\127\1\174\7\127"+
    "\1\0\10\127\1\0\2\127\1\0\1\127\1\0\1\127"+
    "\15\0\2\127\1\0\1\127\3\0\5\127\1\175\3\127"+
    "\1\0\10\127\1\0\2\127\1\0\1\127\1\0\1\127"+
    "\16\0\1\103\2\0\1\101\3\0\2\103\1\46\3\0"+
    "\1\134\6\0\1\103\2\0\1\103\1\0\2\103\1\101"+
    "\1\46\27\0\1\176\44\0\2\53\1\0\2\53\1\104"+
    "\1\0\1\53\1\177\7\53\1\0\10\53\1\105\2\53"+
    "\1\0\1\53\1\0\1\53\15\0\2\53\1\0\2\53"+
    "\1\104\1\0\6\53\1\200\2\53\1\0\10\53\1\105"+
    "\2\53\1\0\1\53\1\0\1\53\15\0\2\53\1\0"+
    "\2\53\1\104\1\0\2\53\1\201\2\53\1\202\3\53"+
    "\1\0\10\53\1\105\2\53\1\0\1\53\1\0\1\53"+
    "\15\0\2\53\1\0\2\53\1\104\1\0\11\53\1\0"+
    "\1\53\1\203\6\53\1\105\2\53\1\0\1\53\1\0"+
    "\1\53\41\0\1\204\30\0\2\53\1\0\2\53\1\104"+
    "\1\0\11\53\1\0\3\53\1\205\4\53\1\105\2\53"+
    "\1\0\1\53\1\0\1\53\15\0\2\53\1\0\2\53"+
    "\1\104\1\0\11\53\1\0\2\53\1\206\5\53\1\105"+
    "\2\53\1\0\1\53\1\0\1\53\15\0\2\53\1\0"+
    "\2\53\1\104\1\0\10\53\1\207\1\0\10\53\1\105"+
    "\2\53\1\0\1\53\1\0\1\53\15\0\2\53\1\0"+
    "\2\53\1\104\1\0\2\53\1\210\6\53\1\0\3\53"+
    "\1\211\4\53\1\105\2\53\1\0\1\53\1\0\1\53"+
    "\15\0\2\53\1\0\2\53\1\104\1\0\11\53\1\212"+
    "\1\213\7\53\1\105\2\53\1\0\1\53\1\0\1\53"+
    "\15\0\2\214\1\0\3\150\1\0\11\214\1\0\10\214"+
    "\1\0\2\214\1\0\1\214\1\0\1\214\26\0\1\215"+
    "\43\0\2\55\1\0\2\55\1\56\1\0\2\55\1\216"+
    "\6\55\1\0\10\55\1\57\2\55\1\0\1\55\1\60"+
    "\1\55\15\0\2\55\1\0\2\55\1\56\1\0\11\55"+
    "\1\0\3\55\1\217\4\55\1\57\2\55\1\0\1\55"+
    "\1\60\1\55\15\0\2\55\1\0\2\55\1\56\1\0"+
    "\10\55\1\220\1\0\10\55\1\57\2\55\1\0\1\55"+
    "\1\60\1\55\15\0\2\55\1\0\2\55\1\56\1\0"+
    "\6\55\1\221\2\55\1\0\10\55\1\57\2\55\1\0"+
    "\1\55\1\60\1\55\15\0\2\55\1\0\2\55\1\56"+
    "\1\0\10\55\1\222\1\0\10\55\1\57\2\55\1\0"+
    "\1\55\1\60\1\55\35\0\2\223\33\0\2\55\1\0"+
    "\2\55\1\56\1\0\11\55\1\223\1\222\7\55\1\57"+
    "\2\55\1\0\1\55\1\60\1\55\15\0\2\55\1\0"+
    "\2\55\1\56\1\0\3\55\1\222\5\55\1\0\10\55"+
    "\1\57\2\55\1\0\1\55\1\60\1\55\15\0\2\55"+
    "\1\0\2\55\1\56\1\0\11\55\1\0\2\55\1\224"+
    "\5\55\1\57\2\55\1\0\1\55\1\60\1\55\15\0"+
    "\2\55\1\0\2\55\1\56\1\0\11\55\1\0\7\55"+
    "\1\222\1\57\2\55\1\0\1\55\1\60\1\55\15\0"+
    "\2\55\1\0\2\55\1\56\1\0\3\55\1\225\5\55"+
    "\1\0\10\55\1\57\2\55\1\0\1\55\1\60\1\55"+
    "\42\0\1\226\27\0\2\55\1\0\2\55\1\56\1\0"+
    "\11\55\1\0\4\55\1\217\3\55\1\57\2\55\1\0"+
    "\1\55\1\60\1\55\15\0\2\167\1\0\3\122\1\0"+
    "\11\167\1\0\10\167\1\57\2\167\1\0\1\167\1\0"+
    "\1\167\15\0\2\227\1\0\3\227\1\0\11\227\1\0"+
    "\10\227\1\0\2\227\1\0\1\227\1\0\1\227\46\0"+
    "\1\230\23\0\2\55\1\0\2\55\1\56\1\231\1\124"+
    "\10\55\1\0\10\55\1\57\2\55\1\0\1\55\1\60"+
    "\1\55\10\0\1\171\4\0\2\127\1\0\1\127\3\0"+
    "\2\127\1\232\6\127\1\0\10\127\1\0\2\127\1\0"+
    "\1\127\1\0\1\127\15\0\2\127\1\0\1\127\3\0"+
    "\7\127\1\233\1\127\1\0\10\127\1\0\2\127\1\0"+
    "\1\127\1\0\1\127\15\0\2\127\1\0\1\127\3\0"+
    "\6\127\1\234\2\127\1\0\10\127\1\0\2\127\1\0"+
    "\1\127\1\0\1\127\26\0\1\235\43\0\2\53\1\0"+
    "\2\53\1\104\1\0\2\53\1\236\6\53\1\0\10\53"+
    "\1\105\2\53\1\0\1\53\1\0\1\53\15\0\2\53"+
    "\1\0\2\53\1\104\1\0\11\53\1\0\3\53\1\237"+
    "\4\53\1\105\2\53\1\0\1\53\1\0\1\53\15\0"+
    "\2\53\1\0\2\53\1\104\1\0\10\53\1\240\1\0"+
    "\10\53\1\105\2\53\1\0\1\53\1\0\1\53\15\0"+
    "\2\53\1\0\2\53\1\104\1\0\6\53\1\241\2\53"+
    "\1\0\10\53\1\105\2\53\1\0\1\53\1\0\1\53"+
    "\15\0\2\53\1\0\2\53\1\104\1\0\10\53\1\242"+
    "\1\0\10\53\1\105\2\53\1\0\1\53\1\0\1\53"+
    "\35\0\2\243\33\0\2\53\1\0\2\53\1\104\1\0"+
    "\11\53\1\243\1\242\7\53\1\105\2\53\1\0\1\53"+
    "\1\0\1\53\15\0\2\53\1\0\2\53\1\104\1\0"+
    "\3\53\1\242\5\53\1\0\10\53\1\105\2\53\1\0"+
    "\1\53\1\0\1\53\15\0\2\53\1\0\2\53\1\104"+
    "\1\0\11\53\1\0\2\53\1\244\5\53\1\105\2\53"+
    "\1\0\1\53\1\0\1\53\15\0\2\53\1\0\2\53"+
    "\1\104\1\0\11\53\1\0\7\53\1\242\1\105\2\53"+
    "\1\0\1\53\1\0\1\53\15\0\2\53\1\0\2\53"+
    "\1\104\1\0\3\53\1\245\5\53\1\0\10\53\1\105"+
    "\2\53\1\0\1\53\1\0\1\53\42\0\1\246\27\0"+
    "\2\53\1\0\2\53\1\104\1\0\11\53\1\0\4\53"+
    "\1\237\3\53\1\105\2\53\1\0\1\53\1\0\1\53"+
    "\15\0\2\214\1\0\3\150\1\0\11\214\1\0\10\214"+
    "\1\105\2\214\1\0\1\214\1\0\1\214\1\0\1\247"+
    "\25\0\1\250\42\0\2\55\1\0\2\55\1\56\1\0"+
    "\3\55\1\251\5\55\1\0\10\55\1\57\2\55\1\0"+
    "\1\55\1\60\1\55\15\0\2\55\1\0\2\55\1\56"+
    "\1\0\11\55\1\0\4\55\1\222\3\55\1\57\2\55"+
    "\1\0\1\55\1\60\1\55\15\0\2\55\1\0\2\55"+
    "\1\56\1\0\1\55\1\252\7\55\1\0\10\55\1\57"+
    "\2\55\1\0\1\55\1\60\1\55\15\0\2\55\1\0"+
    "\2\55\1\56\1\0\4\55\1\253\4\55\1\0\10\55"+
    "\1\57\2\55\1\0\1\55\1\60\1\55\15\0\2\55"+
    "\1\0\2\55\1\56\1\0\4\55\1\222\4\55\1\0"+
    "\10\55\1\57\2\55\1\0\1\55\1\60\1\55\42\0"+
    "\1\223\60\0\1\254\73\0\1\171\4\0\2\127\1\0"+
    "\1\127\3\0\11\127\1\0\2\127\1\255\5\127\1\0"+
    "\2\127\1\0\1\127\1\0\1\127\15\0\2\127\1\0"+
    "\1\127\3\0\4\127\1\256\4\127\1\0\10\127\1\0"+
    "\2\127\1\0\1\127\1\0\1\127\15\0\2\127\1\0"+
    "\1\127\3\0\11\127\1\0\10\127\1\0\2\127\1\0"+
    "\1\127\1\0\1\257\27\0\1\260\42\0\2\53\1\0"+
    "\2\53\1\104\1\0\3\53\1\261\5\53\1\0\10\53"+
    "\1\105\2\53\1\0\1\53\1\0\1\53\15\0\2\53"+
    "\1\0\2\53\1\104\1\0\11\53\1\0\4\53\1\242"+
    "\3\53\1\105\2\53\1\0\1\53\1\0\1\53\15\0"+
    "\2\53\1\0\2\53\1\104\1\0\1\53\1\262\7\53"+
    "\1\0\10\53\1\105\2\53\1\0\1\53\1\0\1\53"+
    "\15\0\2\53\1\0\2\53\1\104\1\0\4\53\1\263"+
    "\4\53\1\0\10\53\1\105\2\53\1\0\1\53\1\0"+
    "\1\53\15\0\2\53\1\0\2\53\1\104\1\0\11\53"+
    "\1\0\10\53\1\105\2\53\1\0\1\53\1\0\1\53"+
    "\1\0\1\247\54\0\1\247\13\0\2\53\1\0\2\53"+
    "\1\104\1\0\3\53\1\242\5\53\1\0\10\53\1\105"+
    "\2\53\1\0\1\53\1\0\1\53\1\0\1\247\13\0"+
    "\2\53\1\0\2\53\1\104\1\0\4\53\1\242\4\53"+
    "\1\0\10\53\1\105\2\53\1\0\1\53\1\0\1\53"+
    "\42\0\1\243\40\0\1\223\43\0\2\55\1\0\2\55"+
    "\1\56\1\0\2\55\1\222\6\55\1\0\10\55\1\57"+
    "\2\55\1\0\1\55\1\60\1\55\15\0\2\55\1\0"+
    "\2\55\1\56\1\0\11\55\1\0\5\55\1\222\2\55"+
    "\1\57\2\55\1\0\1\55\1\60\1\55\15\0\2\55"+
    "\1\0\2\55\1\56\1\223\1\222\6\55\1\264\1\55"+
    "\1\0\10\55\1\57\2\55\1\0\1\55\1\60\1\55"+
    "\15\0\6\265\1\0\11\265\1\0\17\265\4\0\3\265"+
    "\1\0\1\265\1\0\1\266\2\0\2\127\1\0\1\127"+
    "\3\0\11\127\1\0\10\127\1\0\2\127\1\0\1\127"+
    "\1\0\1\127\15\0\2\127\1\0\1\127\3\0\10\127"+
    "\1\267\1\0\10\127\1\0\2\127\1\0\1\127\1\0"+
    "\1\127\15\0\2\127\1\0\1\127\2\0\1\270\1\271"+
    "\10\127\1\0\10\127\1\0\2\127\1\0\1\127\1\0"+
    "\1\127\26\0\1\243\43\0\2\53\1\0\2\53\1\104"+
    "\1\0\2\53\1\242\6\53\1\0\10\53\1\105\2\53"+
    "\1\0\1\53\1\0\1\53\15\0\2\53\1\0\2\53"+
    "\1\104\1\0\11\53\1\0\5\53\1\242\2\53\1\105"+
    "\2\53\1\0\1\53\1\0\1\53\15\0\2\53\1\0"+
    "\2\53\1\104\1\243\1\242\6\53\1\272\1\53\1\0"+
    "\10\53\1\105\2\53\1\0\1\53\1\0\1\53\15\0"+
    "\2\55\1\0\2\55\1\56\1\0\5\55\1\273\3\55"+
    "\1\0\10\55\1\57\2\55\1\0\1\55\1\60\1\55"+
    "\15\0\2\274\4\265\1\0\11\274\1\0\13\274\1\265"+
    "\1\274\1\265\1\274\4\0\3\265\1\0\1\265\1\0"+
    "\1\266\2\0\1\275\2\0\1\275\3\0\11\275\1\0"+
    "\10\275\2\0\1\275\1\0\1\275\1\0\1\275\1\276"+
    "\14\0\2\127\1\0\1\127\3\0\11\127\1\277\1\300"+
    "\7\127\1\0\2\127\1\0\1\127\1\0\1\127\12\0"+
    "\1\301\54\0\1\301\2\0\2\127\1\0\1\127\3\0"+
    "\11\127\1\0\10\127\1\0\2\127\1\0\1\127\1\0"+
    "\1\127\15\0\2\53\1\0\2\53\1\104\1\0\5\53"+
    "\1\302\3\53\1\0\10\53\1\105\2\53\1\0\1\53"+
    "\1\0\1\53\15\0\2\55\1\0\2\55\1\56\1\0"+
    "\10\55\1\303\1\0\10\55\1\57\2\55\1\0\1\55"+
    "\1\60\1\55\15\0\2\304\1\0\1\304\3\0\11\304"+
    "\1\0\10\304\1\0\2\304\1\0\1\304\1\0\1\304"+
    "\15\0\1\305\2\0\1\305\3\0\11\305\1\0\10\305"+
    "\2\0\1\305\1\0\1\305\1\0\1\305\32\0\1\306"+
    "\37\0\2\127\1\0\1\127\3\0\6\127\1\307\2\127"+
    "\1\0\10\127\1\0\2\127\1\0\1\127\1\0\1\127"+
    "\12\0\1\301\2\0\1\310\2\0\1\310\3\0\11\310"+
    "\1\0\10\310\2\0\1\310\1\0\1\310\1\0\1\310"+
    "\15\0\2\53\1\0\2\53\1\104\1\0\10\53\1\311"+
    "\1\0\10\53\1\105\2\53\1\0\1\53\1\0\1\53"+
    "\15\0\2\55\1\0\2\55\1\56\1\0\11\55\1\312"+
    "\1\313\7\55\1\57\2\55\1\0\1\55\1\60\1\55"+
    "\15\0\2\314\1\0\1\314\3\0\11\314\1\0\10\314"+
    "\1\0\2\314\1\0\1\314\1\0\1\314\41\0\1\270"+
    "\30\0\2\127\1\0\1\127\3\0\11\127\1\0\3\127"+
    "\1\271\4\127\1\0\2\127\1\0\1\127\1\0\1\127"+
    "\15\0\2\315\1\0\1\315\3\0\11\315\1\0\10\315"+
    "\1\0\2\315\1\0\1\315\1\0\1\315\15\0\2\53"+
    "\1\0\2\53\1\104\1\0\11\53\1\316\1\317\7\53"+
    "\1\105\2\53\1\0\1\53\1\0\1\53\33\0\1\320"+
    "\36\0\2\55\1\0\2\55\1\56\1\0\7\55\1\321"+
    "\1\55\1\0\10\55\1\57\2\55\1\0\1\55\1\60"+
    "\1\55\15\0\2\314\1\0\1\314\3\0\11\314\1\0"+
    "\10\314\1\0\2\314\1\0\1\314\1\0\1\314\1\0"+
    "\1\322\13\0\2\315\1\0\1\315\1\0\1\323\1\0"+
    "\11\315\1\0\10\315\1\0\2\315\1\0\1\315\1\0"+
    "\1\315\33\0\1\324\36\0\2\53\1\0\2\53\1\104"+
    "\1\0\7\53\1\325\1\53\1\0\10\53\1\105\2\53"+
    "\1\0\1\53\1\0\1\53\23\0\2\223\45\0\2\55"+
    "\1\0\2\55\1\56\1\223\1\222\10\55\1\0\10\55"+
    "\1\57\2\55\1\0\1\55\1\60\1\55\15\0\1\310"+
    "\2\0\1\310\3\0\11\310\1\0\10\310\2\0\1\310"+
    "\1\0\1\310\1\0\1\310\23\0\2\243\45\0\2\53"+
    "\1\0\2\53\1\104\1\243\1\242\10\53\1\0\10\53"+
    "\1\105\2\53\1\0\1\53\1\0\1\53\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8370];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\6\0\1\11\2\1\1\11\2\1\1\11\3\1\4\11"+
    "\5\1\1\11\5\1\1\11\4\1\1\0\1\1\1\0"+
    "\1\11\1\1\14\0\3\11\1\0\1\11\4\0\2\1"+
    "\2\0\1\1\22\0\1\11\4\1\1\11\1\1\32\0"+
    "\1\1\3\0\3\1\24\0\1\1\1\11\1\1\2\0"+
    "\1\1\2\0\3\1\12\0\1\11\5\0\3\1\7\0"+
    "\1\1\1\0\1\1\2\0\1\1\3\0\1\1\3\0"+
    "\1\1\2\0\1\1\5\0\1\1\4\0\1\11\3\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[213];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  /* Must match WhiteSpace regex */
  private final static String WHITE_SPACE = "[ \t\f\r]+";

  // TODO move this into an include file when bug #16053 is fixed
  @Override
  protected int getLineNumber() { return yyline; }
  @Override
  protected void setLineNumber(int x) { yyline = x; }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ScalaXref(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 216) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { writeUnicodeChar(yycharat(0));
            }
          case 29: break;
          case 2: 
            { out.write(yytext());
            }
          case 30: break;
          case 3: 
            { startNewLine();
            }
          case 31: break;
          case 4: 
            { out.write(yycharat(0));
            }
          case 32: break;
          case 5: 
            { out.write("<span class=\"n\">"); out.write(yytext()); out.write("</span>");
            }
          case 33: break;
          case 6: 
            { out.write( "&lt;");
            }
          case 34: break;
          case 7: 
            { out.write( "&gt;");
            }
          case 35: break;
          case 8: 
            { yybegin(STRING);out.write("<span class=\"s\">\"");
            }
          case 36: break;
          case 9: 
            { yybegin(QSTRING);out.write("<span class=\"s\">\'");
            }
          case 37: break;
          case 10: 
            { out.write( "&amp;");
            }
          case 38: break;
          case 11: 
            { yybegin(YYINITIAL); out.write("\"</span>");
            }
          case 39: break;
          case 12: 
            { yybegin(YYINITIAL); out.write("</span>");
    startNewLine();
            }
          case 40: break;
          case 13: 
            { yybegin(YYINITIAL); out.write("'</span>");
            }
          case 41: break;
          case 14: 
            { String id = yytext();
    writeSymbol(id, Consts.kwd, yyline);
            }
          case 42: break;
          case 15: 
            { yybegin(SCOMMENT);out.write("<span class=\"c\">//");
            }
          case 43: break;
          case 16: 
            { yybegin(COMMENT);out.write("<span class=\"c\">/*");
            }
          case 44: break;
          case 17: 
            { out.write("\\\"");
            }
          case 45: break;
          case 18: 
            { out.write("\\\\");
            }
          case 46: break;
          case 19: 
            { yybegin(YYINITIAL); out.write("*/</span>");
            }
          case 47: break;
          case 20: 
            { out.write("\\\'");
            }
          case 48: break;
          case 21: 
            { out.append("<strong>").append(yytext()).append("</strong>");
            }
          case 49: break;
          case 22: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 3);
            { yybegin(JAVADOC);out.write("<span class=\"c\">/**");
            }
          case 50: break;
          case 23: 
            { out.write(Util.breadcrumbPath(urlPrefix+"path=",yytext(),'/'));
            }
          case 51: break;
          case 24: 
            { String path = yytext();
        out.write("<a href=\""+urlPrefix+"path=");
        out.write(path);
        appendProject();
        out.write("\">");
        out.write(path);
        out.write("</a>");
            }
          case 52: break;
          case 25: 
            { writeEMailAddress(yytext());
            }
          case 53: break;
          case 26: 
            { out.write("&lt;");
        String path = yytext();
        path = path.substring(1, path.length() - 1);
        out.write("<a href=\""+urlPrefix+"path=");
        out.write(path);
        appendProject();
        out.write("\">");
        out.write(path);
        out.write("</a>");
        out.write("&gt;");
            }
          case 54: break;
          case 27: 
            { String url = yytext();
         out.write("<a href=\"");
         out.write(url);out.write("\">");
         out.write(url);out.write("</a>");
            }
          case 55: break;
          case 28: 
            { String text = yytext();
    String[] tokens = text.split(WHITE_SPACE, 2);
    out.append("<strong>").append(tokens[0]).append("</strong>")
      .append(text.substring(tokens[0].length(),
                             text.length() - tokens[1].length()))
      .append("<em>").append(tokens[1]).append("</em>");
            }
          case 56: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
