/* The following code was generated by JFlex 1.6.1 */

/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").  
 * You may not use this file except in compliance with the License.
 *
 * See LICENSE.txt included in this distribution for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at LICENSE.txt.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

/*
 * Copyright (c) 2009, 2010, Oracle and/or its affiliates. All rights reserved.
 */

/*
 * Cross reference a Fortran file
 */
package com.grantingersoll.opengrok.analysis.fortran;
import com.grantingersoll.opengrok.analysis.JFlexXref;
import java.io.IOException;
import java.io.Writer;
import java.io.Reader;
import com.grantingersoll.opengrok.web.Util;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/Users/grantingersoll/projects/OpenGrok/src/org/opensolaris/opengrok/analysis/fortran/FortranXref.lex</tt>
 */
public class FortranXref extends JFlexXref {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int COMMENT = 4;
  public static final int SCOMMENT = 6;
  public static final int QSTRING = 8;
  public static final int LCOMMENT = 10;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6, 6
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\1\0\1\1\1\2\22\0\1\1\1\30\1\26"+
    "\1\34\2\6\1\33\1\27\2\34\1\32\2\6\1\10\1\11\1\16"+
    "\1\17\11\5\1\43\1\6\1\24\1\6\1\25\1\6\1\44\2\21"+
    "\1\15\2\21\1\42\1\4\1\35\1\13\4\4\1\14\1\4\1\37"+
    "\2\4\1\41\1\36\3\4\1\20\2\4\1\34\1\31\2\34\1\7"+
    "\1\34\2\21\1\15\1\23\1\21\1\42\1\4\1\35\1\13\2\4"+
    "\1\22\1\4\1\14\1\4\1\37\2\4\1\41\1\36\1\22\2\4"+
    "\1\20\2\4\3\34\1\6\6\0\1\0\252\0\2\12\115\0\1\40"+
    "\u1ea8\0\1\0\1\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\7\0\1\1\1\2\2\3\1\4\1\5\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\5"+
    "\3\4\1\6\1\15\4\4\1\2\2\16\1\17\1\4"+
    "\1\20\1\21\1\0\1\5\12\0\1\22\1\23\2\0"+
    "\1\24\1\0\1\25\2\5\7\0\1\2\7\0\1\26"+
    "\6\0\2\27\1\30\4\0\1\31\2\0\1\32";

  private static int [] zzUnpackAction() {
    int [] result = new int[93];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\112\0\157\0\224\0\271\0\336\0\u0103"+
    "\0\u0128\0\u014d\0\u0103\0\u0172\0\u0197\0\u0103\0\u01bc\0\u01e1"+
    "\0\u0103\0\u0103\0\u0103\0\u0103\0\u0103\0\u0206\0\u022b\0\u0250"+
    "\0\u0275\0\u029a\0\u0103\0\u02bf\0\u02e4\0\u0309\0\u032e\0\u0353"+
    "\0\u0378\0\u039d\0\u0103\0\u03c2\0\u03e7\0\u0103\0\u0172\0\u040c"+
    "\0\u0431\0\u0456\0\u047b\0\u04a0\0\u0250\0\u04c5\0\u04ea\0\u050f"+
    "\0\u0275\0\u0534\0\u0559\0\u0103\0\u0103\0\u057e\0\u05a3\0\u0103"+
    "\0\u05c8\0\u0103\0\u05ed\0\u0612\0\u0637\0\u065c\0\u0681\0\u06a6"+
    "\0\u06cb\0\u06f0\0\u0715\0\u0103\0\u073a\0\u075f\0\u0784\0\u07a9"+
    "\0\u07ce\0\u07f3\0\u0818\0\u083d\0\u0862\0\u0887\0\u08ac\0\u08d1"+
    "\0\u08f6\0\u091b\0\u0103\0\u0250\0\u0862\0\u0940\0\u0965\0\u098a"+
    "\0\u09af\0\u0103\0\u09d4\0\u09f9\0\u09f9";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[93];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\14"+
    "\2\16\1\10\3\14\1\16\1\17\4\14\1\20\1\21"+
    "\1\22\1\23\1\24\2\16\1\25\1\16\3\14\1\10"+
    "\2\14\2\16\1\26\1\11\1\12\1\13\1\26\1\27"+
    "\11\26\1\27\25\26\1\10\1\11\1\12\1\13\1\30"+
    "\1\31\1\16\3\31\1\10\3\30\1\32\1\31\4\30"+
    "\1\33\1\21\1\34\2\16\1\35\1\16\1\25\1\16"+
    "\1\36\2\30\1\10\1\30\1\37\2\16\1\10\1\11"+
    "\1\12\1\13\1\30\1\31\1\16\3\31\1\10\3\30"+
    "\1\32\1\31\4\30\1\33\1\21\4\16\1\40\1\25"+
    "\1\16\1\36\2\30\1\10\1\30\1\37\2\16\1\10"+
    "\1\41\1\42\1\43\1\30\1\31\1\16\3\31\1\10"+
    "\3\30\1\32\1\31\4\30\1\33\1\21\5\16\1\25"+
    "\1\16\1\36\2\30\1\10\1\30\1\37\2\16\1\10"+
    "\1\11\1\12\1\13\1\30\1\31\1\16\3\31\1\10"+
    "\3\30\1\32\1\31\4\30\1\33\1\21\1\16\1\44"+
    "\1\16\1\45\1\16\1\25\1\16\1\36\2\30\1\10"+
    "\1\30\1\37\2\16\1\46\1\41\1\42\1\43\6\16"+
    "\1\46\11\16\1\33\1\21\5\16\1\25\4\16\1\46"+
    "\4\16\46\0\1\11\1\12\1\13\44\0\1\13\45\0"+
    "\2\47\1\0\1\47\3\0\3\47\1\0\5\47\11\0"+
    "\3\47\1\0\2\47\7\0\1\15\3\0\1\50\5\0"+
    "\1\15\2\0\2\51\26\0\1\15\3\0\1\50\5\0"+
    "\1\15\1\52\1\0\2\51\25\0\1\53\6\0\3\53"+
    "\1\54\1\0\4\53\11\0\3\53\1\0\2\53\2\0"+
    "\1\26\3\0\42\26\3\0\1\26\1\27\11\26\1\27"+
    "\25\26\4\0\2\55\1\0\2\55\1\56\1\0\3\55"+
    "\1\57\5\55\11\0\3\55\1\0\2\55\1\0\1\60"+
    "\4\0\2\61\1\0\3\61\1\0\3\61\1\0\5\61"+
    "\11\0\3\61\1\0\2\61\1\0\1\60\4\0\1\62"+
    "\6\0\3\62\2\0\4\62\11\0\3\62\1\0\2\62"+
    "\3\0\1\63\71\0\1\64\2\0\1\65\17\0\2\55"+
    "\1\0\2\55\1\56\1\0\3\55\1\57\5\55\11\0"+
    "\1\55\1\66\1\55\1\0\2\55\1\0\1\60\4\0"+
    "\2\55\1\0\2\55\1\56\1\0\3\55\1\57\5\55"+
    "\11\0\1\55\1\67\1\55\1\0\2\55\1\0\1\60"+
    "\16\0\1\70\27\0\1\41\1\42\1\43\44\0\1\43"+
    "\42\0\1\71\72\0\1\72\1\0\1\65\20\0\1\73"+
    "\11\0\1\73\47\0\2\51\26\0\1\74\7\0\1\74"+
    "\1\0\1\74\1\0\1\74\1\0\1\74\16\0\1\74"+
    "\6\0\2\53\1\0\2\53\1\75\1\0\3\53\1\76"+
    "\5\53\11\0\3\53\1\0\2\53\6\0\1\77\6\0"+
    "\3\77\2\0\4\77\11\0\3\77\1\0\2\77\6\0"+
    "\2\55\1\0\2\55\1\56\1\100\1\101\2\55\1\57"+
    "\5\55\11\0\3\55\1\0\2\55\1\0\1\60\4\0"+
    "\1\102\6\0\3\102\2\0\4\102\11\0\3\102\1\0"+
    "\2\102\6\0\2\103\1\0\3\103\1\0\3\103\1\0"+
    "\5\103\11\0\3\103\1\0\2\103\6\0\2\62\1\0"+
    "\3\62\1\0\3\62\1\57\5\62\11\0\3\62\1\0"+
    "\2\62\3\0\1\63\24\0\1\104\22\0\2\55\1\0"+
    "\2\55\1\56\1\0\3\55\1\57\5\55\11\0\1\55"+
    "\1\105\1\55\1\0\2\55\1\0\1\60\4\0\2\55"+
    "\1\0\2\55\1\56\1\0\3\55\1\57\5\55\11\0"+
    "\2\55\1\106\1\0\2\55\1\0\1\60\1\0\1\71"+
    "\25\0\1\104\22\0\1\73\11\0\1\73\2\0\2\51"+
    "\26\0\1\74\7\0\1\74\1\0\1\74\1\0\1\74"+
    "\1\51\1\74\16\0\1\74\6\0\2\53\1\0\2\53"+
    "\1\75\1\107\1\110\2\53\1\76\5\53\11\0\3\53"+
    "\1\0\2\53\6\0\1\111\6\0\3\111\2\0\4\111"+
    "\11\0\3\111\1\0\2\111\6\0\2\77\1\0\3\77"+
    "\1\0\3\77\1\76\5\77\11\0\3\77\1\0\2\77"+
    "\16\0\1\112\34\0\2\55\1\0\2\55\1\56\1\0"+
    "\1\55\1\113\1\55\1\57\5\55\11\0\3\55\1\0"+
    "\2\55\1\0\1\60\4\0\2\114\1\0\3\102\1\0"+
    "\3\114\1\0\5\114\11\0\3\114\1\0\2\114\6\0"+
    "\2\103\1\0\2\103\1\115\1\0\3\103\1\0\5\103"+
    "\11\0\3\103\1\0\2\103\6\0\2\55\1\0\2\55"+
    "\1\56\1\0\3\55\1\57\5\55\11\0\2\55\1\116"+
    "\1\0\2\55\1\0\1\60\4\0\2\55\1\0\2\55"+
    "\1\56\1\0\3\55\1\57\5\55\11\0\3\55\1\0"+
    "\2\55\1\117\1\60\14\0\1\120\34\0\2\53\1\0"+
    "\2\53\1\75\1\0\1\53\1\121\1\53\1\76\5\53"+
    "\11\0\3\53\1\0\2\53\6\0\2\122\1\0\3\111"+
    "\1\0\3\122\1\0\5\122\11\0\3\122\1\0\2\122"+
    "\17\0\1\123\33\0\2\55\1\0\2\55\1\56\1\0"+
    "\2\55\1\124\1\57\5\55\11\0\3\55\1\0\2\55"+
    "\1\0\1\60\4\0\2\114\1\0\3\102\1\0\3\114"+
    "\1\57\5\114\11\0\3\114\1\0\2\114\6\0\2\125"+
    "\1\0\3\125\1\0\3\125\1\0\5\125\11\0\3\125"+
    "\1\0\2\125\6\0\2\55\1\0\2\55\1\56\1\0"+
    "\3\55\1\57\5\55\11\0\3\55\1\126\1\106\1\55"+
    "\1\117\1\60\16\0\1\127\43\0\1\130\33\0\2\53"+
    "\1\0\2\53\1\75\1\0\2\53\1\131\1\76\5\53"+
    "\11\0\3\53\1\0\2\53\6\0\2\122\1\0\3\111"+
    "\1\0\3\122\1\76\5\122\1\0\1\132\7\0\3\122"+
    "\1\0\2\122\45\0\1\117\17\0\1\133\53\0\1\132"+
    "\23\0\2\53\1\0\2\53\1\75\1\0\3\53\1\76"+
    "\5\53\1\0\1\132\7\0\3\53\1\0\2\53\6\0"+
    "\6\134\1\0\11\134\4\0\4\134\1\0\3\134\1\0"+
    "\4\134\4\0\2\135\4\134\1\0\11\135\4\0\4\134"+
    "\1\0\3\135\1\0\2\135\2\134";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2590];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\7\0\1\11\2\1\1\11\2\1\1\11\2\1\5\11"+
    "\5\1\1\11\7\1\1\11\2\1\1\11\1\1\1\0"+
    "\1\1\12\0\2\11\2\0\1\11\1\0\1\11\2\1"+
    "\7\0\1\11\7\0\1\1\6\0\1\11\2\1\4\0"+
    "\1\11\2\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[93];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  // TODO move this into an include file when bug #16053 is fixed
  @Override
  protected int getLineNumber() { return yyline; }
  @Override
  protected void setLineNumber(int x) { yyline = x; }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public FortranXref(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 200) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { 
            }
          case 27: break;
          case 2: 
            { out.write(yytext());
            }
          case 28: break;
          case 3: 
            { startNewLine();
            }
          case 29: break;
          case 4: 
            { out.write(yycharat(0));
            }
          case 30: break;
          case 5: 
            { out.write("<span class=\"n\">"); out.write(yytext()); out.write("</span>");
            }
          case 31: break;
          case 6: 
            { out.write( "&lt;");
            }
          case 32: break;
          case 7: 
            { out.write( "&gt;");
            }
          case 33: break;
          case 8: 
            { yybegin(STRING);out.write("<span class=\"s\">\"");
            }
          case 34: break;
          case 9: 
            { yybegin(QSTRING);out.write("<span class=\"s\">\'");
            }
          case 35: break;
          case 10: 
            { yybegin(SCOMMENT);out.write("<span class=\"c\">!");
            }
          case 36: break;
          case 11: 
            { out.write( "&amp;");
            }
          case 37: break;
          case 12: 
            { String commentStr = yytext(); yybegin(LCOMMENT);out.write("<span class=\"c\">"+commentStr);
            }
          case 38: break;
          case 13: 
            { yybegin(YYINITIAL); out.write("\"</span>");
            }
          case 39: break;
          case 14: 
            { yybegin(YYINITIAL); out.write("</span>");
                  startNewLine();
            }
          case 40: break;
          case 15: 
            { yybegin(YYINITIAL); out.write("'</span>");
            }
          case 41: break;
          case 16: 
            { writeUnicodeChar(yycharat(0));
            }
          case 42: break;
          case 17: 
            { String id = yytext();
    writeSymbol(id, Consts.kwd, yyline);
            }
          case 43: break;
          case 18: 
            { out.write("\\\"");
            }
          case 44: break;
          case 19: 
            { out.write("\\\\");
            }
          case 45: break;
          case 20: 
            { yybegin(YYINITIAL); out.write("*/</span>");
            }
          case 46: break;
          case 21: 
            { out.write("\\\'");
            }
          case 47: break;
          case 22: 
            { out.write(Util.breadcrumbPath(urlPrefix+"path=",yytext(),'/'));
            }
          case 48: break;
          case 23: 
            { String path = yytext();
        out.write("<a href=\""+urlPrefix+"path=");
        out.write(path);out.write("\">");
        out.write(path);out.write("</a>");
            }
          case 49: break;
          case 24: 
            { writeEMailAddress(yytext());
            }
          case 50: break;
          case 25: 
            { out.write("&lt;");
    String file = yytext();
    file = file.substring(1, file.length() - 1);
    out.write("<a href=\""+urlPrefix+"path=");
    out.write(file);out.write("\">");
    out.write(file);out.write("</a>");
    out.write("&gt;");
            }
          case 51: break;
          case 26: 
            { String url = yytext();
         out.write("<a href=\"");
         out.write(url);out.write("\">");
         out.write(url);out.write("</a>");
            }
          case 52: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
