/* The following code was generated by JFlex 1.6.1 */

/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").
 * You may not use this file except in compliance with the License.
 *
 * See LICENSE.txt included in this distribution for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at LICENSE.txt.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

/*
 * Copyright (c) 2015, Oracle and/or its affiliates. All rights reserved.
 */

/*
 * Cross reference a Haskell file
 */

package com.grantingersoll.opengrok.analysis.haskell;
import com.grantingersoll.opengrok.analysis.JFlexXref;
import com.grantingersoll.opengrok.web.Util;

/**
 * @author Harry Pan
 */


public class HaskellXref extends JFlexXref {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHAR = 4;
  public static final int COMMENT = 6;
  public static final int BCOMMENT = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\1\24\1\25\1\2\22\0\1\1\1\10\1\21"+
    "\1\0\2\10\1\27\1\5\2\0\1\10\1\20\1\10\1\6\1\16"+
    "\1\12\1\13\11\7\1\40\1\10\1\30\1\10\1\31\1\10\1\41"+
    "\4\15\1\17\1\37\1\4\1\32\7\4\1\34\2\4\1\36\1\33"+
    "\3\4\1\14\2\4\1\0\1\23\2\0\1\11\1\0\4\15\1\17"+
    "\1\37\1\4\1\32\7\4\1\34\2\4\1\36\1\33\3\4\1\14"+
    "\2\4\1\22\1\0\1\26\1\10\6\0\1\24\371\0\1\35\u1ea8\0"+
    "\1\24\1\24\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\2\3\1\4\1\5\1\1\2\6"+
    "\1\7\1\1\1\10\1\11\1\12\1\2\2\13\3\1"+
    "\1\14\4\1\1\2\1\1\1\10\1\11\1\12\1\1"+
    "\1\15\1\6\3\0\1\16\5\0\1\17\1\20\2\0"+
    "\1\21\1\0\1\21\1\22\1\6\1\0\2\6\4\0"+
    "\1\6\1\23\3\0\1\24\4\0\1\25";

  private static int [] zzUnpackAction() {
    int [] result = new int[74];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\42\0\104\0\146\0\210\0\252\0\314\0\356"+
    "\0\252\0\u0110\0\252\0\u0132\0\u0154\0\u0176\0\252\0\u0198"+
    "\0\252\0\252\0\252\0\u01ba\0\u01dc\0\252\0\u01fe\0\u0220"+
    "\0\u0242\0\252\0\u0264\0\u0286\0\u02a8\0\u02ca\0\u02ec\0\u030e"+
    "\0\u02ca\0\u02ca\0\u02ca\0\u0330\0\252\0\u0352\0\u0374\0\u0396"+
    "\0\u03b8\0\252\0\u01fe\0\u03da\0\u03fc\0\u0220\0\u041e\0\252"+
    "\0\252\0\u0440\0\u0462\0\252\0\u02ca\0\u02ca\0\252\0\u0484"+
    "\0\u04a6\0\u04a6\0\u04c8\0\u04ea\0\u050c\0\u052e\0\u0550\0\u0572"+
    "\0\u0594\0\u05b6\0\u05d8\0\u05fa\0\u05b6\0\u061c\0\u063e\0\u0660"+
    "\0\u0682\0\u0682";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[74];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\6\1\12\1\6\1\16\2\12\1\6\1\12\1\6"+
    "\1\17\1\20\2\6\1\7\1\6\1\21\1\22\1\23"+
    "\3\12\1\6\2\12\3\6\1\24\1\25\1\26\1\27"+
    "\1\6\2\30\1\6\1\30\1\31\1\30\2\27\1\30"+
    "\1\27\1\6\1\32\1\6\1\33\1\6\1\24\1\6"+
    "\1\21\1\22\1\23\1\34\2\27\1\6\1\27\1\35"+
    "\2\6\1\36\1\37\1\25\1\26\17\36\1\40\1\6"+
    "\1\24\1\36\1\41\1\42\1\43\10\36\1\6\1\24"+
    "\1\25\1\26\1\27\1\6\2\30\1\6\1\30\1\31"+
    "\1\30\2\27\1\30\1\27\5\6\1\24\1\6\1\21"+
    "\1\22\1\23\1\34\2\27\1\6\1\27\1\35\3\6"+
    "\1\7\1\10\1\11\1\27\1\6\1\44\1\30\1\6"+
    "\1\30\1\31\1\30\2\27\1\30\1\27\5\6\1\7"+
    "\1\6\1\21\1\22\1\23\1\34\2\27\1\6\1\27"+
    "\1\35\2\6\43\0\1\7\1\10\1\11\21\0\1\7"+
    "\17\0\1\11\42\0\2\12\1\0\1\12\1\0\1\12"+
    "\1\0\3\12\1\0\1\12\12\0\3\12\1\0\2\12"+
    "\10\0\1\45\42\0\1\15\1\0\1\46\1\0\1\15"+
    "\2\0\1\47\1\50\31\0\1\15\1\0\1\46\1\0"+
    "\1\15\1\51\1\0\1\47\1\50\30\0\1\52\34\0"+
    "\1\24\1\25\1\26\21\0\1\24\17\0\1\26\42\0"+
    "\1\53\1\0\2\53\1\0\1\53\1\54\5\53\12\0"+
    "\3\53\1\0\2\53\1\0\1\55\4\0\1\56\1\0"+
    "\2\56\1\0\1\56\1\0\5\56\12\0\3\56\1\0"+
    "\2\56\1\0\1\55\4\0\1\57\7\0\2\57\1\0"+
    "\1\57\12\0\3\57\1\0\2\57\23\0\1\60\1\0"+
    "\1\61\22\0\1\53\1\0\2\53\1\0\1\53\1\54"+
    "\5\53\12\0\1\53\1\62\1\53\1\0\2\53\1\0"+
    "\1\55\4\0\1\53\1\0\2\53\1\0\1\53\1\54"+
    "\5\53\12\0\1\53\1\63\1\53\1\0\2\53\1\0"+
    "\1\55\5\0\1\64\35\0\1\24\1\25\1\26\1\0"+
    "\1\64\17\0\1\24\14\0\2\65\2\0\1\65\1\66"+
    "\16\65\2\0\14\65\4\0\1\56\1\0\2\56\1\0"+
    "\1\56\1\0\5\56\6\0\1\67\3\0\3\56\1\0"+
    "\2\56\1\0\1\55\7\0\1\46\1\0\1\46\1\0"+
    "\1\46\3\0\1\50\31\0\1\70\3\0\1\70\34\0"+
    "\1\71\1\72\3\0\1\72\4\0\1\71\30\0\1\73"+
    "\3\0\1\73\1\0\1\73\1\0\1\73\17\0\1\73"+
    "\6\0\1\74\7\0\2\74\1\0\1\74\12\0\3\74"+
    "\1\0\2\74\6\0\1\75\1\0\2\75\1\0\1\75"+
    "\1\0\5\75\12\0\3\75\1\0\2\75\6\0\1\57"+
    "\1\0\2\57\1\0\1\57\1\54\5\57\12\0\3\57"+
    "\1\0\2\57\6\0\1\53\1\0\2\53\1\0\1\53"+
    "\1\54\5\53\12\0\1\53\1\76\1\53\1\0\2\53"+
    "\1\0\1\55\4\0\1\53\1\0\2\53\1\0\1\53"+
    "\1\54\5\53\12\0\2\53\1\77\1\0\2\53\1\0"+
    "\1\55\7\0\1\70\3\0\1\70\3\0\1\50\31\0"+
    "\1\72\3\0\1\72\35\0\1\73\3\0\1\73\1\0"+
    "\1\73\1\0\1\100\17\0\1\73\6\0\1\101\1\0"+
    "\1\74\1\101\1\0\1\74\1\0\3\101\1\74\1\101"+
    "\12\0\3\101\1\0\2\101\6\0\1\75\1\0\2\75"+
    "\1\0\1\75\1\0\3\75\1\102\1\75\12\0\3\75"+
    "\1\0\2\75\6\0\1\53\1\0\2\53\1\0\1\53"+
    "\1\54\5\53\12\0\2\53\1\103\1\0\2\53\1\0"+
    "\1\55\4\0\1\53\1\0\2\53\1\0\1\53\1\54"+
    "\5\53\12\0\3\53\1\0\2\53\1\104\1\55\6\0"+
    "\1\71\1\73\3\0\1\73\1\0\1\73\1\0\1\100"+
    "\1\71\16\0\1\73\6\0\1\101\1\0\1\74\1\101"+
    "\1\0\1\74\1\54\3\101\1\74\1\101\12\0\3\101"+
    "\1\0\2\101\6\0\1\105\1\0\2\105\1\0\1\105"+
    "\1\0\5\105\12\0\3\105\1\0\2\105\6\0\1\53"+
    "\1\0\2\53\1\0\1\53\1\54\5\53\12\0\3\53"+
    "\1\106\1\77\1\53\1\104\1\55\12\0\1\107\67\0"+
    "\1\104\13\0\1\110\33\0\1\111\1\0\13\111\2\0"+
    "\1\111\3\0\1\111\2\0\3\111\1\0\4\111\4\0"+
    "\1\112\1\0\1\111\1\112\2\111\4\112\1\111\1\112"+
    "\1\111\2\0\1\111\3\0\1\111\2\0\3\112\1\0"+
    "\2\112\2\111";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1700];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\2\1\1\11\1\1\1\11\3\1\1\11"+
    "\1\1\3\11\2\1\1\11\3\1\1\11\12\1\1\11"+
    "\1\1\3\0\1\11\5\0\2\11\2\0\1\11\1\0"+
    "\1\1\1\11\1\1\1\0\2\1\4\0\2\1\3\0"+
    "\1\1\4\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[74];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  // TODO move this into an include file when bug #16053 is fixed
  @Override
  protected int getLineNumber() { return yyline; }
  @Override
  protected void setLineNumber(int x) { yyline = x; }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public HaskellXref(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 178) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { writeUnicodeChar(yycharat(0));
            }
          case 22: break;
          case 2: 
            { out.write(yytext());
            }
          case 23: break;
          case 3: 
            { startNewLine();
            }
          case 24: break;
          case 4: 
            { String id = yytext();
        writeSymbol(id, Consts.kwd, yyline);
            }
          case 25: break;
          case 5: 
            { yybegin(CHAR); out.write("<span class=\"s\">\'");
            }
          case 26: break;
          case 6: 
            { out.write("<span class=\"n\">"); out.write(yytext()); out.write("</span>");
            }
          case 27: break;
          case 7: 
            { yybegin(STRING); out.write("<span class=\"s\">\"");
            }
          case 28: break;
          case 8: 
            { out.write( "&amp;");
            }
          case 29: break;
          case 9: 
            { out.write( "&lt;");
            }
          case 30: break;
          case 10: 
            { out.write( "&gt;");
            }
          case 31: break;
          case 11: 
            { yybegin(YYINITIAL); out.write("</span>"); startNewLine();
            }
          case 32: break;
          case 12: 
            { yybegin(YYINITIAL); out.write("\"</span>");
            }
          case 33: break;
          case 13: 
            { yybegin(COMMENT); out.write("<span class=\"c\">--");
            }
          case 34: break;
          case 14: 
            { yybegin(BCOMMENT); out.write("<span class=\"c\">{-");
            }
          case 35: break;
          case 15: 
            { out.write("\\\"");
            }
          case 36: break;
          case 16: 
            { out.write("\\\\");
            }
          case 37: break;
          case 17: 
            { yybegin(YYINITIAL); out.write(yytext()); out.write("</span>");
            }
          case 38: break;
          case 18: 
            { yybegin(YYINITIAL); out.write("-}</span>");
            }
          case 39: break;
          case 19: 
            { out.write(Util.breadcrumbPath(urlPrefix + "path=", yytext(), '/'));
            }
          case 40: break;
          case 20: 
            { writeEMailAddress(yytext());
            }
          case 41: break;
          case 21: 
            { String url = yytext();
        out.write("<a href=\"");
        out.write(url); out.write("\">");
        out.write(url); out.write("</a>");
            }
          case 42: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
